# **Indonesian Food Nutrition: Dataset Development, Analysis, and Estimation Using YOLOv8n**

Notebook ini mendokumentasikan proses pengembangan sistem Food Recognition dan Estimasi Nilai Gizi Makanan Indonesia menggunakan pendekatan deep learning berbasis object detection. Proyek ini berfokus pada bagaimana model dapat mengenali berbagai jenis makanan Indonesia dari satu gambar (single-image approach) dan menghubungkannya dengan data nutrisi lokal untuk menghasilkan estimasi kalori dan komposisi gizi.

Metode utama yang digunakan adalah YOLOv8m, yang merupakan versi menengah dari keluarga YOLOv8 dengan keseimbangan antara akurasi dan efisiensi komputasi. Model ini dipilih karena mampu mendeteksi banyak objek makanan dalam satu citra sekaligus, sekaligus mempertahankan performa yang stabil.

Disusun oleh Legio 6:
- Ratu Rinjanhei Macinnes (01082230039)
- Joy ()
- Kent
- Vincent

## **Environment Setup**

Bab ini berfungsi sebagai fondasi teknis yang menjamin stabilitas dan kompatibilitas lingkungan sebelum model YOLOv8m dijalankan. Seluruh konfigurasi dilakukan untuk meminimalkan konflik dependensi dan memastikan proses pelatihan berjalan optimal baik di CPU maupun GPU. Tanpa tahap ini, risiko error saat training, seperti mismatch versi library, memory conflict, atau kegagalan CUDA, akan meningkat secara signifikan.

### 1. Downgrade dan Instalasi NumPy

In [ ]:
# Downgrade numpy agar kompatibel dengan modul yang kamu pakai
%pip install numpy==1.26.4 --force-reinstall

Bagian ini bertujuan untuk memastikan versi NumPy yang digunakan kompatibel dengan library deep learning yang akan dipakai, terutama PyTorch dan Ultralytics (YOLOv8).
Beberapa versi terbaru NumPy sering menimbulkan konflik dengan modul yang bergantung pada API lama, sehingga dilakukan downgrade ke versi stabil 1.26.4 agar lingkungan tetap konsisten dan menghindari error saat proses training dan inferensi.

### 2. Instalasi Library Utama untuk Object Detection

In [1]:
%pip install ultralytics==8.3.50 opencv-python==4.10.0.84 pandas matplotlib torch torchvision torchaudio pytorch-grad-cam==1.4.8 --extra-index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
  Using cached ultralytics-8.3.50-py3-none-any.whl.metadata (35 kB)
  Using cached opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement pytorch-grad-cam==1.4.8 (from versions: none)
ERROR: No matching distribution found for pytorch-grad-cam==1.4.8


Bagian ini menginstal seluruh library inti yang digunakan dalam proyek, yaitu:

- **ultralytics** : library utama untuk menjalankan YOLOv8 (object detection dan training).
- **opencv-python** : digunakan untuk pemrosesan citra dan manipulasi visual.
- **torch, torchvision, torchaudio** : fondasi deep learning berbasis PyTorch untuk training dan inferensi.
- **pandas & matplotlib** : membantu analisis data dan visualisasi hasil training.
- **pytorch-grad-cam** : digunakan untuk visualisasi area fokus model (interpretabilitas model).
- **extra-index-url CUDA 12.1** : memastikan PyTorch menggunakan GPU NVIDIA dengan akselerasi CUDA untuk meningkatkan kecepatan komputasi.

Tahap ini memastikan lingkungan siap untuk proses pelatihan YOLOv8m secara optimal dan efisien.

### 3. Import Library dan Validasi Lingkungan

In [2]:
import torch, cv2, numpy as np
from ultralytics import YOLO

print("Torch:", torch.__version__, "| CUDA:", torch.cuda.is_available())
print("NumPy:", np.__version__)
print("OpenCV:", cv2.__version__)

Torch: 2.3.1+cu121 | CUDA: True
NumPy: 1.26.4
OpenCV: 4.8.1


Output ini berfungsi sebagai checkpoint teknis awal untuk memastikan bahwa sistem siap digunakan sebelum masuk ke tahap preprocessing, training, dan evaluasi YOLOv8m.

## **Preprocessing**

### 1. Dataset Configuration & Class ID Remapping
Bagian ini mendefinisikan lokasi utama dataset serta file konfigurasi data.yaml yang digunakan YOLO untuk membaca daftar kelas dan struktur dataset. Dengan menentukan path ini secara eksplisit, seluruh proses pemetaan kelas dilakukan langsung terhadap dataset asli tanpa mengubah struktur folder secara manual.

Tujuannya adalah memastikan seluruh perubahan kelas tetap konsisten dan terdokumentasi secara sistematis.

Proses dimulai dengan membaca daftar kelas asli dari data.yaml, kemudian dilakukan aturan transformasi kelas yang akan diterapkan:
- **rename_map**: Digunakan untuk standarisasi penamaan kelas agar konsisten (contoh: "nasi goreng" → "Nasi Goreng").

- **merge_map**: Digunakan untuk menggabungkan dua kelas yang memiliki makna sama atau terlalu mirip secara visual (contoh: "Rujak" dilebur ke "Rujak Buah").

- **delete_classes**:Menentukan kelas yang sepenuhnya dihapus dari dataset karena tidak digunakan dalam penelitian atau dianggap mengganggu keseimbangan data.

Setelah itu, sistem membentuk ulang daftar kelas final yang telah dibersihkan dan bebas duplikasi. Selanjutnya, dibuat pemetaan ID dari indeks kelas lama ke indeks kelas baru untuk memastikan seluruh label bounding box tetap valid setelah perubahan struktur kelas. Tahap ini bertujuan menjaga integritas anotasi, mencegah kesalahan indeks, serta meningkatkan kualitas dan keterbacaan dataset sebelum digunakan dalam proses training YOLOv8m.

In [3]:
import yaml
import os
from glob import glob
import shutil

# --- PATH UTAMA ---
# Ganti path ini sesuai dengan lokasi folder "Food Dataset" Anda
DATASET_PATH = r"C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset"
YAML_PATH = os.path.join(DATASET_PATH, "data.yaml")

# --- PARAMETER PREPROCESSING ---
rename_map = {
    "nasi goreng": "Nasi Goreng",
    "pecel lele": "Pecel Lele",
    "rawon": "Rawon",
    "sate": "Sate",
}

merge_map = {
    "Rujak": "Rujak Buah" # Rujak akan dilebur ke Rujak Buah
}

delete_classes = ["Pecel Lele", "Bubur Ayam", "Ayam Goreng"]

# --- LOAD DATA ASLI ---
with open(YAML_PATH, "r") as f:
    data = yaml.safe_load(f)

original_classes = data["names"]
print(f"Kelas Asli ({len(original_classes)}): {original_classes}")

# --- PEMBENTUKAN KELAS FINAL DAN ID MAP ---

processed_names = []
for cls in original_classes:
    # 1. Rename
    name = rename_map.get(cls.lower(), cls)
    # 2. Merge
    name = merge_map.get(name, name)
    processed_names.append(name)

# 3. Hapus Duplikat dan Kelas yang dihapus
new_classes = []
for name in processed_names:
    if name not in delete_classes and name not in new_classes:
        new_classes.append(name)

print(f"Kelas Final ({len(new_classes)}): {new_classes}")

# --- PEMBENTUKAN ID MAP (Lama -> Baru) ---
id_map_fix = {}

for old_idx, old_name in enumerate(original_classes):
    # Terapkan rename dan merge
    name_temp = rename_map.get(old_name.lower(), old_name)
    name_final = merge_map.get(name_temp, name_temp)

    if name_final in delete_classes:
        # Kelas ini akan dihapus
        id_map_fix[old_idx] = None
    else:
        # Kelas dipertahankan atau di-merge, cari index barunya
        try:
            new_idx = new_classes.index(name_final)
            id_map_fix[old_idx] = new_idx
        except ValueError:
            # Seharusnya tidak terjadi jika logic di atas benar
            print(f"ERROR: Kelas {name_final} tidak ditemukan di kelas baru!")
            id_map_fix[old_idx] = None

print(f"ID Map (Lama -> Baru/None): {id_map_fix}")

Kelas Asli (21): ['Ayam Goreng', 'Bakso', 'Bubur Ayam', 'Cakwe', 'Dadar Gulung', 'Ikan Goreng', 'Klepon', 'Lontong Sayur', 'Martabak Manis', 'Mie Goreng', 'Nasi Padang', 'Rendang', 'Risol', 'Rujak', 'Rujak Buah', 'Sayur Asem', 'Soto Ayam', 'nasi goreng', 'pecel lele', 'rawon', 'sate']
Kelas Final (17): ['Bakso', 'Cakwe', 'Dadar Gulung', 'Ikan Goreng', 'Klepon', 'Lontong Sayur', 'Martabak Manis', 'Mie Goreng', 'Nasi Padang', 'Rendang', 'Risol', 'Rujak Buah', 'Sayur Asem', 'Soto Ayam', 'Nasi Goreng', 'Rawon', 'Sate']
ID Map (Lama -> Baru/None): {0: None, 1: 0, 2: None, 3: 1, 4: 2, 5: 3, 6: 4, 7: 5, 8: 6, 9: 7, 10: 8, 11: 9, 12: 10, 13: 11, 14: 11, 15: 12, 16: 13, 17: 14, 18: None, 19: 15, 20: 16}


Hasil preprocessing menunjukkan bahwa **dataset awal memiliki 21 kelas**, namun setelah dilakukan standarisasi nama, penggabungan, dan penghapusan kelas, jumlahnya **menjadi 17 kelas final**. Beberapa kelas seperti Ayam Goreng, Bubur Ayam, dan pecel lele dihapus secara sengaja karena tidak termasuk dalam ruang lingkup penelitian, sementara perbedaan penulisan seperti "nasi goreng" dan "rawon" berhasil distandarkan menjadi format yang seragam. Selain itu, kelas Rujak berhasil dilebur ke dalam Rujak Buah, mengurangi redundansi semantik yang berpotensi membingungkan model saat proses pembelajaran.

Peta ID (Old → New) menunjukkan bahwa beberapa indeks lama dipetakan ke None, yang menandakan kelas tersebut dihapus sepenuhnya dari dataset, sementara kelas lain dipetakan ulang ke indeks baru yang lebih terstruktur. Proses ini memastikan bahwa setiap bounding box tetap memiliki referensi kelas yang valid dan tidak terjadi kesalahan indeks saat training YOLOv8m.

### 2. Pembaruan File Label
Bagian ini melakukan pembersihan dan sinkronisasi file label YOLO agar sepenuhnya selaras dengan struktur kelas baru yang telah distandarisasi sebelumnya. Setiap file label pada split train, valid, dan test dipindai untuk memperbarui ID kelas berdasarkan peta id_map_fix. Bounding box dari kelas yang dihapus otomatis dieliminasi, sementara bounding box yang valid disesuaikan dengan indeks kelas baru. Jika suatu file label menjadi kosong setelah proses ini, maka file label beserta gambar pasangannya turut dihapus untuk menjaga konsistensi dataset dan mencegah data kosong masuk ke proses training.

In [4]:
# --- FUNGSI PEMBARUAN LABEL AMAN ---

def safe_process_labels(split):
    label_dir = os.path.join(DATASET_PATH, split, "labels")
    img_dir = os.path.join(DATASET_PATH, split, "images")

    # Pastikan direktori labels ada
    if not os.path.isdir(label_dir):
        print(f"Direktori labels untuk {split} tidak ditemukan di: {label_dir}")
        return

    label_files = glob(label_dir + "/*.txt")
    
    deleted_file_count = 0
    modified_file_count = 0

    print(f"\n--- Memproses Split: {split.upper()} ({len(label_files)} file) ---")

    for txt_path in label_files:
        with open(txt_path, "r") as f:
            lines = f.readlines()
        
        new_lines = []
        is_modified = False

        for line in lines:
            parts = line.strip().split()
            if not parts or len(parts) < 5:
                continue
                
            old_id = int(parts[0])
            
            # Cari ID baru
            new_id = id_map_fix.get(old_id) 
            
            if new_id is not None:
                # BBox Dipertahankan: Update ID baru
                if old_id != new_id:
                    parts[0] = str(new_id)
                    is_modified = True
                
                new_lines.append(" ".join(parts))
            else:
                # BBox Dihapus: Abaikan baris ini
                is_modified = True
        
        # JIKA label menjadi KOSONG atau BUKAN label kosong tapi ada modifikasi
        if not new_lines:
            # Hapus file label dan gambar
            os.remove(txt_path)
            img_path = os.path.join(img_dir, os.path.basename(txt_path).replace(".txt", ".jpg"))
            if os.path.exists(img_path):
                os.remove(img_path)
            deleted_file_count += 1
            
        elif is_modified:
            # Tulis ulang file label dengan BBox yang telah difilter/diperbarui ID-nya
            with open(txt_path, "w") as f:
                f.write("\n".join(new_lines) + "\n")
            modified_file_count += 1
            
    print(f"File label/gambar dihapus (label kosong): {deleted_file_count}")
    print(f"File label diupdate (difilter/ganti ID): {modified_file_count}")
    print("-" * 30)

# Jalankan proses untuk setiap split
safe_process_labels("train")
safe_process_labels("valid")
safe_process_labels("test")

# --- FINAL UPDATE data.yaml ---
data["train"] = f"{DATASET_PATH}/train/images"
data["val"] = f"{DATASET_PATH}/valid/images"
data["test"] = f"{DATASET_PATH}/test/images"
data["names"] = new_classes
data["nc"] = len(new_classes)

with open(YAML_PATH, "w") as f:
    yaml.safe_dump(data, f, sort_keys=False) # sort_keys=False menjaga urutan

print("✔ data.yaml telah diperbarui dengan path absolute dan kelas final!")
print(f"Total kelas baru (nc): {len(new_classes)}")


--- Memproses Split: TRAIN (2579 file) ---
File label/gambar dihapus (label kosong): 303
File label diupdate (difilter/ganti ID): 2276
------------------------------

--- Memproses Split: VALID (737 file) ---
File label/gambar dihapus (label kosong): 89
File label diupdate (difilter/ganti ID): 648
------------------------------

--- Memproses Split: TEST (368 file) ---
File label/gambar dihapus (label kosong): 39
File label diupdate (difilter/ganti ID): 329
------------------------------
✔ data.yaml telah diperbarui dengan path absolute dan kelas final!
Total kelas baru (nc): 17


Hasil proses menunjukkan bahwa dataset mengalami pemurnian signifikan. Pada split train, sebanyak 303 gambar dihapus karena tidak lagi memiliki label valid, sementara 2276 file lainnya diperbarui agar sesuai dengan struktur baru. Hal serupa terjadi pada valid (89 file dihapus, 648 diperbarui) dan test (39 file dihapus, 329 diperbarui). Ini mengindikasikan bahwa sebagian data awal memang didominasi oleh kelas yang kemudian dihilangkan atau di-merge, sehingga perlu dilakukan filtering agresif untuk menjaga kualitas anotasi.

Pembaruan akhir pada data.yaml memastikan bahwa path dataset dan daftar kelas telah mengikuti konfigurasi final sebanyak 17 kelas, sehingga seluruh pipeline YOLOv8m kini berjalan di atas dataset yang bersih, konsisten, dan bebas dari label usang. Secara keseluruhan, tahap ini meningkatkan integritas data, mengurangi noise pada proses training, serta mencegah kesalahan indeks yang dapat menurunkan performa model atau menyebabkan crash saat pelatihan.

In [5]:
import os
from glob import glob
import yaml
from collections import Counter

# --- VARIABEL UTAMA (Pastikan DATASET_PATH dan new_classes sudah terdefinisi) ---
DATASET_PATH = r"C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset"
YAML_PATH = os.path.join(DATASET_PATH, "data.yaml")

# Muat data.yaml terbaru untuk mendapatkan nama kelas final
with open(YAML_PATH, "r") as f:
    data_final = yaml.safe_load(f)

new_classes = data_final["names"] # Kelas hasil preprocessing
nc = data_final["nc"]

# Inisialisasi penghitung untuk semua kelas
class_counts = Counter()
total_files = 0
total_bbox = 0
splits = ["train", "valid", "test"]

print("=========================================")
print("  ANALISIS DISTRIBUSI KELAS (BBOX COUNT) ")
print("=========================================")

for split in splits:
    label_dir = os.path.join(DATASET_PATH, split, "labels")
    label_files = glob(label_dir + "/*.txt")
    total_files += len(label_files)
    
    # Penghitung per split
    split_counts = Counter()
    
    for txt_path in label_files:
        try:
            with open(txt_path, "r") as f:
                lines = f.readlines()
            
            for line in lines:
                parts = line.strip().split()
                if parts and len(parts) >= 5:
                    class_id = int(parts[0])
                    # Tambahkan ke penghitung split dan total
                    split_counts[class_id] += 1
                    class_counts[class_id] += 1
                    total_bbox += 1
        
        except Exception as e:
            print(f"Error membaca file {txt_path}: {e}")

    # Tampilkan hasil per split (Opsional, untuk detail)
    # print(f"\n--- {split.upper()} (Total File: {len(label_files)}) ---")
    # for class_id in range(nc):
    #     class_name = new_classes[class_id]
    #     count = split_counts.get(class_id, 0)
    #     print(f"  {class_id:2d} {class_name:<15}: {count}")


print("\n=========================================")
print(f"✅ HASIL FINAL (Total {nc} Kelas)")
print(f"Total File Gambar/Label Tersisa: {total_files}")
print(f"Total Bounding Box Keseluruhan: {total_bbox}")
print("=========================================")

# Tampilkan hasil total yang diformat
print("\n[ ID | Nama Kelas | Total BBox ]")
print("-----------------------------------")
for class_id in range(nc):
    class_name = new_classes[class_id]
    count = class_counts.get(class_id, 0)
    
    # Cetak dengan warna merah jika jumlahnya 0
    if count == 0:
        print(f"❌ {class_id:2d} | {class_name:<15} | {count} <-- KOSONG!")
    else:
        print(f"   {class_id:2d} | {class_name:<15} | {count}")

print("-----------------------------------")

  ANALISIS DISTRIBUSI KELAS (BBOX COUNT) 

✅ HASIL FINAL (Total 17 Kelas)
Total File Gambar/Label Tersisa: 3253
Total Bounding Box Keseluruhan: 7575

[ ID | Nama Kelas | Total BBox ]
-----------------------------------
    0 | Bakso           | 111
    1 | Cakwe           | 830
    2 | Dadar Gulung    | 1006
    3 | Ikan Goreng     | 509
    4 | Klepon          | 1625
    5 | Lontong Sayur   | 202
    6 | Martabak Manis  | 767
    7 | Mie Goreng      | 175
    8 | Nasi Padang     | 220
    9 | Rendang         | 267
   10 | Risol           | 576
   11 | Rujak Buah      | 198
   12 | Sayur Asem      | 203
   13 | Soto Ayam       | 224
   14 | Nasi Goreng     | 224
   15 | Rawon           | 239
   16 | Sate            | 199
-----------------------------------


Distribusi bounding box menunjukkan adanya ketidakseimbangan antar kelas. Beberapa kelas memiliki representasi sangat tinggi seperti Klepon (1625 bbox) dan Dadar Gulung (1006 bbox), sementara kelas lain seperti Bakso (111 bbox) dan Mie Goreng (175 bbox) memiliki jumlah yang jauh lebih rendah. Ini mengindikasikan potensi class imbalance yang dapat menyebabkan model lebih bias terhadap kelas dengan jumlah data besar saat training.

Namun, tidak ditemukan kelas dengan jumlah bounding box nol, yang berarti seluruh kelas final benar-benar memiliki data representatif dan layak untuk dipelajari oleh model. Hal ini memperlihatkan bahwa proses filtering sebelumnya berhasil menjaga integritas dataset tanpa mengorbankan keberadaan kelas penting.

### 3. Downsampling (Pengurangan Data)
Tahap ini bertujuan untuk mengurangi ketimpangan distribusi data (class imbalance) dengan cara menurunkan jumlah sampel pada kelas yang memiliki bounding box terlalu dominan. Dalam kasus ini, kelas Dadar Gulung (ID 2) dan Klepon (ID 4) dipilih karena jumlah bounding box-nya jauh lebih tinggi dibanding kelas lain. Target yang ditetapkan adalah sekitar 550 bounding box per kelas agar distribusi data menjadi lebih proporsional.

Proses dilakukan secara aman dengan mengidentifikasi file gambar yang mengandung kelas target, kemudian menghitung estimasi jumlah file yang perlu dipertahankan berdasarkan rata-rata bounding box per file. File yang melebihi batas tersebut dipilih secara acak (random sampling) dan dipindahkan ke folder excess_data, bukan dihapus permanen, sehingga dataset tetap memiliki cadangan untuk kebutuhan evaluasi atau eksperimen ulang.

In [7]:
import os
import random
from glob import glob
import shutil
import yaml
from collections import Counter

# --- KONFIGURASI ---
# Path Anda (Pastikan sudah benar)
DATASET_PATH = r"C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset"
YAML_PATH = os.path.join(DATASET_PATH, "data.yaml")

# Muat data.yaml terbaru untuk nama kelas final
with open(YAML_PATH, "r") as f:
    data_final = yaml.safe_load(f)
new_classes = data_final["names"]

# Kelas yang akan dikurangi (Berdasarkan ID di output Anda)
# ID 2: Dadar Gulung (1006 BBox)
# ID 4: Klepon (1625 BBox)
CLASSES_TO_REDUCE = [2, 4] 

# Target BBox count: Kita akan hitung target image count berdasarkan target BBox
TARGET_BBOX_COUNT = 550 # Target BBox per kelas setelah downsample

# Folder tujuan untuk menyimpan data yang dihapus (untuk keamanan)
EXCESS_DIR = os.path.join(DATASET_PATH, "excess_data")
os.makedirs(EXCESS_DIR, exist_ok=True)

# --- FUNGSI DOWN SAMPLING ---

def downsample_class_images(split="train"):
    print(f"\n--- Memulai Downsampling pada split: {split.upper()} ---")
    
    label_dir = os.path.join(DATASET_PATH, split, "labels")
    img_dir = os.path.join(DATASET_PATH, split, "images")
    label_files = glob(label_dir + "/*.txt")
    
    # Map untuk menyimpan semua file yang mengandung kelas target
    class_file_map = {cls_id: [] for cls_id in CLASSES_TO_REDUCE}
    
    # 1. IDENTIFIKASI FILE GAMBAR YANG MENGANDUNG KELAS TARGET
    current_bbox_counts = Counter()
    
    for txt_path in label_files:
        with open(txt_path, "r") as f:
            lines = f.readlines()
            
        # Set untuk mengetahui kelas apa saja yang ada di file ini
        classes_in_file = set()
        
        for line in lines:
            parts = line.strip().split()
            if parts and len(parts) >= 5:
                class_id = int(parts[0])
                current_bbox_counts[class_id] += 1
                classes_in_file.add(class_id)
        
        # Tambahkan file ke map jika mengandung kelas yang ingin dikurangi
        for cls_id in CLASSES_TO_REDUCE:
            if cls_id in classes_in_file:
                class_file_map[cls_id].append(txt_path)


    # 2. HITUNG DAN HAPUS KELEBIHAN FILE
    files_to_remove = set()
    
    for cls_id in CLASSES_TO_REDUCE:
        class_name = new_classes[cls_id]
        total_bbox = current_bbox_counts.get(cls_id, 0)
        
        if total_bbox <= TARGET_BBOX_COUNT:
            print(f"[{class_name}] OK: BBox Count {total_bbox} (<= {TARGET_BBOX_COUNT}). Tidak perlu dikurangi.")
            continue
            
        files_for_class = class_file_map[cls_id]
        
        # --- Estimasi Target File Count ---
        # Untuk menentukan berapa banyak file yang harus dihapus, kita menggunakan rasio.
        # Estimasi rata-rata BBox per file untuk kelas ini
        avg_bbox_per_file = total_bbox / len(files_for_class) if files_for_class else 1
        
        # Perkiraan jumlah file yang harus dipertahankan
        target_file_count = int(TARGET_BBOX_COUNT / avg_bbox_per_file)
        
        files_to_delete_count = len(files_for_class) - target_file_count

        if files_to_delete_count > 0:
            # Ambil sampel acak dari file yang akan dihapus
            files_to_delete = random.sample(files_for_class, files_to_delete_count)
            files_to_remove.update(files_to_delete) # Gunakan 'set' untuk menghindari duplikasi
            
            print(f"[{class_name}] REDUCE: BBox Asli {total_bbox}. Target File Keep: {target_file_count}. Menghapus {files_to_delete_count} file.")
        else:
            print(f"[{class_name}] OK: BBox Count {total_bbox}. Target file count sudah tercapai.")

    # 3. EKSEKUSI PENGHAPUSAN (Memindahkan ke folder EXCESS_DIR)
    removed_count = 0
    
    for txt_path in files_to_remove:
        # Pindahkan file label
        shutil.move(txt_path, os.path.join(EXCESS_DIR, os.path.basename(txt_path)))
        
        # Cari dan Pindahkan file gambar
        file_name_no_ext = os.path.basename(txt_path).replace(".txt", "")
        img_path = os.path.join(img_dir, f"{file_name_no_ext}.jpg") # Asumsi format .jpg
        if not os.path.exists(img_path):
            # Coba format .png jika .jpg tidak ada
            img_path = os.path.join(img_dir, f"{file_name_no_ext}.png")
            
        if os.path.exists(img_path):
            shutil.move(img_path, os.path.join(EXCESS_DIR, os.path.basename(img_path)))
        
        removed_count += 1

    print(f"\n--- Selesai Downsampling ---")
    print(f"Total file gambar/label yang dipindahkan (dihapus): {removed_count}")
    print(f"File berlebihan disimpan di: {EXCESS_DIR}")
    
# --- Jalankan Downsampling HANYA pada data 'train' ---
downsample_class_images("train")


--- Memulai Downsampling pada split: TRAIN ---
[Dadar Gulung] REDUCE: BBox Asli 781. Target File Keep: 80. Menghapus 35 file.
[Klepon] REDUCE: BBox Asli 1085. Target File Keep: 70. Menghapus 70 file.

--- Selesai Downsampling ---
Total file gambar/label yang dipindahkan (dihapus): 105
File berlebihan disimpan di: C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\excess_data


Hasilnya, pada split train:
- Dadar Gulung dikurangi dari 781 bbox dengan menghapus 35 file gambar.
- Klepon dikurangi dari 1085 bbox dengan menghapus 70 file gambar.

Total terdapat 105 file yang dipindahkan dari dataset utama.

**Mengapa Hanya Split train?**

- Pelatihan: Data train digunakan untuk mengajarkan model. Menyeimbangkan kelas di sini akan mengurangi bias.
- Validasi/Test: Data valid dan test harus mencerminkan distribusi kelas yang sebenarnya di dunia nyata. Jika di dunia nyata Klepon lebih banyak muncul, data valid dan test harus tetap mengandung lebih banyak Klepon untuk menguji performa model secara realistis.

In [8]:
import os
from glob import glob
import yaml
from collections import Counter

# --- KONFIGURASI PATH ---
DATASET_PATH = r"C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset"
YAML_PATH = os.path.join(DATASET_PATH, "data.yaml")

# Muat data.yaml terbaru untuk mendapatkan nama kelas final
with open(YAML_PATH, "r") as f:
    data_final = yaml.safe_load(f)

new_classes = data_final["names"] 
nc = data_final["nc"]

# Inisialisasi penghitung
class_counts = Counter()
total_files = 0
total_bbox = 0
splits = ["train", "valid", "test"]

print("=========================================")
print("  ANALISIS DISTRIBUSI KELAS (BBOX COUNT) ")
print("=========================================")

for split in splits:
    label_dir = os.path.join(DATASET_PATH, split, "labels")
    label_files = glob(label_dir + "/*.txt")
    total_files += len(label_files)
    
    for txt_path in label_files:
        try:
            with open(txt_path, "r") as f:
                lines = f.readlines()
            
            for line in lines:
                parts = line.strip().split()
                if parts and len(parts) >= 5:
                    class_id = int(parts[0])
                    class_counts[class_id] += 1
                    total_bbox += 1
        
        except Exception as e:
            print(f"Error membaca file {txt_path}: {e}")

print("\n=========================================")
print(f"✅ HASIL FINAL (Total {nc} Kelas)")
print(f"Total File Gambar/Label Tersisa: {total_files}")
print(f"Total Bounding Box Keseluruhan: {total_bbox}")
print("=========================================")

# Tampilkan hasil total yang diformat
print("\n[ ID | Nama Kelas | Total BBox ]")
print("-----------------------------------")
for class_id in range(nc):
    class_name = new_classes[class_id]
    count = class_counts.get(class_id, 0)
    
    # Cetak dengan tanda seru jika jumlahnya 0 atau masih tinggi (di atas 600)
    indicator = " "
    if count == 0:
        indicator = "❌"
    elif count > 600:
        indicator = "⚠️"
        
    print(f"{indicator} {class_id:2d} | {class_name:<15} | {count}")

print("-----------------------------------")

  ANALISIS DISTRIBUSI KELAS (BBOX COUNT) 

✅ HASIL FINAL (Total 17 Kelas)
Total File Gambar/Label Tersisa: 3148
Total Bounding Box Keseluruhan: 6738

[ ID | Nama Kelas | Total BBox ]
-----------------------------------
   0 | Bakso           | 111
⚠️  1 | Cakwe           | 830
⚠️  2 | Dadar Gulung    | 777
   3 | Ikan Goreng     | 505
⚠️  4 | Klepon          | 1021
   5 | Lontong Sayur   | 202
⚠️  6 | Martabak Manis  | 767
   7 | Mie Goreng      | 175
   8 | Nasi Padang     | 220
   9 | Rendang         | 267
  10 | Risol           | 576
  11 | Rujak Buah      | 198
  12 | Sayur Asem      | 203
  13 | Soto Ayam       | 224
  14 | Nasi Goreng     | 224
  15 | Rawon           | 239
  16 | Sate            | 199
-----------------------------------


Beberapa kelas seperti Klepon (1021 bbox), Cakwe (830 bbox), Dadar Gulung (777 bbox), dan Martabak Manis (767 bbox) masih berada di atas ambang 600 bounding box dan ditandai sebagai ⚠️. Namun, kondisi ini masih tergolong aman untuk pelatihan YOLOv8, karena **rasio distribusi antar kelas masih berada dalam rentang yang bisa ditoleransi oleh mekanisme loss balancing dan optimasi bawaan YOLO**

YOLOv8 secara internal menggunakan mekanisme seperti class-aware loss weighting, IoU-based optimization, dan dynamic anchor matching, yang membuatnya cukup robust terhadap ketidakseimbangan moderat seperti ini. Dengan demikian, distribusi saat ini sudah berada pada kondisi yang stabil, di mana model tidak akan terlalu bias terhadap satu kelas tertentu, namun tetap memiliki cukup variasi data untuk mempelajari fitur visual setiap jenis makanan.

## Training YOLOv8m

In [10]:
from ultralytics import YOLO
import torch
import os

# --- KONFIGURASI PATH ---
# Ganti path ini ke lokasi file data.yaml final Anda
DATA_YAML_PATH = r"C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\data.yaml"

# Pastikan path data sudah benar
if not os.path.exists(DATA_YAML_PATH):
    raise FileNotFoundError(f"File data.yaml tidak ditemukan di: {DATA_YAML_PATH}")

# --- LOAD MODEL DAN DEVICE ---
# Load base model (medium)
print("Mengunduh dan memuat model yolov8m.pt...")
model = YOLO("yolov8m.pt")

# Tentukan Device: GPU (0) atau CPU
device = 0 if torch.cuda.is_available() else "cpu"
print(f"Menggunakan Device: {device}")

# --- PARAMETER PELATIHAN ---
# Catatan: Jika imgsz=768 dan batch=4 masih menyebabkan OOM pada GPU kecil, 
# coba kurangi imgsz menjadi 640 atau batch menjadi 2.

train_results = model.train(
    data=DATA_YAML_PATH,
    epochs=200,             # Jumlah total epochs
    patience=30,            # Early Stopping (setelah 30 epoch tanpa perbaikan)
    imgsz=768,              # Ukuran gambar input (768x768)
    batch=4,                # Batch size (Disesuaikan)
    device=device,
    
    # 🔥 Optimizer & Learning Rate strategy
    optimizer="AdamW",      # Direkomendasikan untuk fine-tuning
    lr0=0.001,              # Initial Learning Rate
    cos_lr=True,            # Menggunakan Cosine LR Scheduler (baik untuk fine-tuning)
    warmup_epochs=5,        # Warming up LR selama 5 epoch
    weight_decay=0.0005,
    
    # 🔥 Augmentations (Tidak diubah, ini sudah baik)
    hsv_h=0.012, hsv_s=0.6, hsv_v=0.35,
    degrees=4, translate=0.10, scale=0.40, shear=0.05, perspective=0.0,
    fliplr=0.5, flipud=0.15, mosaic=0.20, mixup=0.05, erasing=0.25,
    multi_scale=False,
    
    # 🔥 Logging Baru
    project="indonesian_food_yolov8", # Nama folder proyek utama
    name="yolov8m_balance_run",       # Nama folder hasil pelatihan spesifik
    exist_ok=True,
)

print("\n✔ Pelatihan dimulai!")
print(f"Hasil akan disimpan di folder: runs/detect/indonesian_food_yolov8/yolov8m_balance_run")

Mengunduh dan memuat model yolov8m.pt...
Menggunakan Device: 0
New https://pypi.org/project/ultralytics/8.3.231 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.74  Python-3.10.11 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB)
engine\trainer: task=detect, mode=train, model=yolov8m.pt, data=C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\data.yaml, epochs=200, time=None, patience=30, batch=4, imgsz=768, save=True, save_period=-1, cache=False, device=0, workers=8, project=indonesian_food_yolov8, name=yolov8m_balance_run, exist_ok=True, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=

train: Scanning C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\train\labels.cache... 2171 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2171/2171 [00:00<?, ?it/s]

WARNING  Box and segment counts should be equal, but got len(segments) = 3235, len(boxes) = 4467. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.



val: Scanning C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\valid\labels.cache... 648 images, 0 backgrounds, 0 corrupt: 100%|██████████| 648/648 [00:00<?, ?it/s]

WARNING  Box and segment counts should be equal, but got len(segments) = 1100, len(boxes) = 1520. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.


Plotting labels to indonesian_food_yolov8\yolov8m_balance_run\labels.jpg... 
optimizer: AdamW(lr=0.001, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 768 train, 768 val
Using 8 dataloader workers
Logging results to indonesian_food_yolov8\yolov8m_balance_run
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      1/200      4.38G      1.296      3.094      1.912          5        768: 100%|██████████| 543/543 [01:26<00:00,  6.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.62it/s]

                   all        648       1520      0.245      0.322      0.212      0.126



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      2/200      3.36G      1.392      2.846       1.99         13        768: 100%|██████████| 543/543 [01:30<00:00,  5.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.85it/s]

                   all        648       1520      0.318      0.403      0.268      0.165



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      3/200      3.33G       1.35      2.757      1.957          3        768: 100%|██████████| 543/543 [01:30<00:00,  6.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  7.48it/s]


                   all        648       1520      0.289      0.408      0.267      0.172

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      4/200      3.33G      1.339      2.649      1.958         12        768: 100%|██████████| 543/543 [01:24<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.30it/s]

                   all        648       1520      0.409      0.387      0.343      0.226



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      5/200      3.32G      1.309       2.56      1.944         11        768: 100%|██████████| 543/543 [01:20<00:00,  6.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.35it/s]

                   all        648       1520      0.282      0.447      0.302        0.2



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      6/200      3.32G      1.293      2.468      1.906          3        768: 100%|██████████| 543/543 [01:21<00:00,  6.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.69it/s]

                   all        648       1520      0.304      0.509      0.354      0.232



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      7/200      3.34G      1.231      2.383      1.844          7        768: 100%|██████████| 543/543 [01:23<00:00,  6.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  7.84it/s]


                   all        648       1520      0.401      0.496      0.411      0.282

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      8/200      3.36G      1.196      2.245      1.802          6        768: 100%|██████████| 543/543 [01:23<00:00,  6.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  8.10it/s]

                   all        648       1520      0.448      0.548      0.478      0.334



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      9/200      3.33G      1.186      2.151      1.792         22        768: 100%|██████████| 543/543 [01:22<00:00,  6.55it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.36it/s]

                   all        648       1520      0.477      0.561      0.513      0.365



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     10/200      3.33G       1.17      2.133      1.761          9        768: 100%|██████████| 543/543 [01:24<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.58it/s]

                   all        648       1520      0.466      0.528      0.501      0.349



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     11/200      3.33G      1.136      2.075      1.726          4        768: 100%|██████████| 543/543 [01:24<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.69it/s]

                   all        648       1520      0.474      0.579      0.552        0.4



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     12/200      3.33G      1.111      1.952       1.71          9        768: 100%|██████████| 543/543 [01:22<00:00,  6.55it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.14it/s]

                   all        648       1520      0.504      0.621      0.561      0.406



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     13/200      3.32G       1.11      1.956       1.72         17        768: 100%|██████████| 543/543 [01:24<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.55it/s]

                   all        648       1520      0.504      0.541      0.547      0.409



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     14/200      3.32G      1.074      1.919      1.667          9        768: 100%|██████████| 543/543 [01:23<00:00,  6.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.17it/s]

                   all        648       1520      0.557      0.559       0.58      0.419



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     15/200      3.33G      1.061      1.823      1.661          9        768: 100%|██████████| 543/543 [01:24<00:00,  6.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.47it/s]

                   all        648       1520      0.584      0.618      0.623       0.46



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     16/200      3.32G      1.042      1.768      1.647          5        768: 100%|██████████| 543/543 [01:24<00:00,  6.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.15it/s]

                   all        648       1520      0.573      0.595      0.641      0.455



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     17/200      3.31G      1.055      1.789      1.647         11        768: 100%|██████████| 543/543 [01:27<00:00,  6.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.55it/s]

                   all        648       1520      0.601      0.616      0.642      0.474



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     18/200      3.32G      1.032      1.742      1.624          4        768: 100%|██████████| 543/543 [01:27<00:00,  6.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  7.84it/s]


                   all        648       1520      0.623      0.669      0.687      0.511

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     19/200      3.32G      1.011      1.667      1.605          3        768: 100%|██████████| 543/543 [01:34<00:00,  5.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.61it/s]

                   all        648       1520      0.619      0.632      0.661      0.479



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     20/200      3.32G     0.9907       1.61      1.579          3        768: 100%|██████████| 543/543 [01:33<00:00,  5.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.60it/s]

                   all        648       1520      0.617      0.658      0.656      0.466



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     21/200      3.32G      1.002       1.63      1.589         19        768: 100%|██████████| 543/543 [01:33<00:00,  5.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  7.66it/s]

                   all        648       1520      0.652      0.665      0.686      0.493



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     22/200      3.32G     0.9761       1.57      1.577         11        768: 100%|██████████| 543/543 [01:30<00:00,  5.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.50it/s]

                   all        648       1520      0.638      0.681      0.715      0.523



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     23/200      3.33G     0.9624      1.521      1.561          3        768: 100%|██████████| 543/543 [01:29<00:00,  6.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  7.81it/s]

                   all        648       1520      0.685      0.677      0.714      0.531



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     24/200      3.36G     0.9652       1.51      1.544          3        768: 100%|██████████| 543/543 [01:29<00:00,  6.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  7.79it/s]

                   all        648       1520      0.627      0.723      0.711      0.522



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     25/200      3.32G     0.9881      1.485      1.584         13        768: 100%|██████████| 543/543 [01:27<00:00,  6.17it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.78it/s]


                   all        648       1520      0.706       0.69      0.759      0.562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     26/200      3.33G     0.9639      1.501      1.567          4        768: 100%|██████████| 543/543 [01:27<00:00,  6.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.63it/s]

                   all        648       1520      0.771      0.664      0.765      0.563



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     27/200      3.33G     0.9345      1.421      1.525          5        768: 100%|██████████| 543/543 [01:24<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  7.68it/s]

                   all        648       1520      0.715      0.725       0.78      0.585



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     28/200      3.32G       0.92      1.376      1.504          4        768: 100%|██████████| 543/543 [01:24<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.14it/s]

                   all        648       1520      0.693      0.727      0.768      0.566



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     29/200      3.32G     0.9355      1.374      1.527          5        768: 100%|██████████| 543/543 [01:22<00:00,  6.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.26it/s]

                   all        648       1520      0.728      0.743       0.79       0.57



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     30/200      3.33G     0.9294      1.367      1.526          3        768: 100%|██████████| 543/543 [01:23<00:00,  6.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.48it/s]

                   all        648       1520      0.748      0.731      0.782      0.584



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     31/200      3.32G     0.9238       1.35      1.512          3        768: 100%|██████████| 543/543 [01:20<00:00,  6.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.21it/s]

                   all        648       1520      0.708      0.741      0.791      0.601



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     32/200      3.32G     0.8965      1.316      1.488         29        768: 100%|██████████| 543/543 [01:21<00:00,  6.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.27it/s]

                   all        648       1520      0.731       0.74      0.787      0.584



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     33/200      3.32G     0.8837      1.274      1.482          5        768: 100%|██████████| 543/543 [01:22<00:00,  6.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.37it/s]

                   all        648       1520      0.746      0.727      0.797      0.604



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     34/200      3.32G     0.8867      1.224      1.462         15        768: 100%|██████████| 543/543 [01:20<00:00,  6.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.52it/s]


                   all        648       1520      0.728      0.716      0.757      0.567

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     35/200      3.32G      0.886      1.232      1.472          9        768: 100%|██████████| 543/543 [01:20<00:00,  6.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.36it/s]

                   all        648       1520      0.768      0.749       0.81       0.59



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     36/200      3.32G     0.8908      1.207      1.468          6        768: 100%|██████████| 543/543 [01:22<00:00,  6.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.44it/s]

                   all        648       1520      0.783      0.756      0.813      0.607



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     37/200      3.33G     0.8867      1.232      1.467          9        768: 100%|██████████| 543/543 [01:23<00:00,  6.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.41it/s]

                   all        648       1520      0.738      0.714       0.79      0.584



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     38/200      3.31G     0.8796      1.179       1.46          8        768: 100%|██████████| 543/543 [01:24<00:00,  6.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.10it/s]

                   all        648       1520      0.776      0.747      0.808      0.613



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     39/200      3.32G      0.872      1.207      1.448          3        768: 100%|██████████| 543/543 [01:23<00:00,  6.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.11it/s]

                   all        648       1520      0.758      0.764      0.816      0.613



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     40/200      3.36G     0.8657      1.154      1.443         14        768: 100%|██████████| 543/543 [01:23<00:00,  6.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.11it/s]

                   all        648       1520       0.77      0.755      0.826      0.611



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     41/200      3.32G     0.8658      1.152      1.447          5        768: 100%|██████████| 543/543 [01:23<00:00,  6.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.98it/s]

                   all        648       1520      0.783      0.761      0.826      0.623



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     42/200      3.33G     0.8347      1.115      1.423          7        768: 100%|██████████| 543/543 [01:23<00:00,  6.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.09it/s]

                   all        648       1520        0.8      0.766      0.836      0.627



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     43/200      3.33G     0.8442      1.083      1.428          6        768: 100%|██████████| 543/543 [01:21<00:00,  6.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.54it/s]

                   all        648       1520      0.789      0.776      0.824      0.634



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     44/200      3.33G     0.8219      1.071      1.407         10        768: 100%|██████████| 543/543 [01:22<00:00,  6.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.80it/s]


                   all        648       1520      0.784      0.776      0.827       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     45/200      3.32G     0.8456      1.072      1.427          6        768: 100%|██████████| 543/543 [01:23<00:00,  6.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.16it/s]

                   all        648       1520      0.812      0.775      0.836      0.642



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     46/200      3.32G     0.8419      1.095      1.436          3        768: 100%|██████████| 543/543 [01:20<00:00,  6.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.15it/s]

                   all        648       1520      0.796      0.756      0.837      0.642



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     47/200      3.33G     0.8475       1.07      1.423         11        768: 100%|██████████| 543/543 [01:21<00:00,  6.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.80it/s]

                   all        648       1520      0.801      0.786      0.842       0.65



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     48/200      3.32G     0.8537      1.113      1.435          5        768: 100%|██████████| 543/543 [01:22<00:00,  6.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.86it/s]

                   all        648       1520      0.808      0.782      0.845      0.643



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     49/200      3.32G     0.8291      1.048      1.406          3        768: 100%|██████████| 543/543 [01:23<00:00,  6.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.28it/s]

                   all        648       1520      0.804      0.799      0.845      0.638



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     50/200      3.33G     0.8194       1.05      1.395          8        768: 100%|██████████| 543/543 [01:22<00:00,  6.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.73it/s]

                   all        648       1520      0.803      0.786      0.838      0.643



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     51/200      3.32G     0.8373      1.044      1.406          5        768: 100%|██████████| 543/543 [01:23<00:00,  6.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:15<00:00,  5.18it/s]

                   all        648       1520       0.79       0.77       0.84      0.646



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     52/200      3.32G     0.7985      0.999      1.373          6        768: 100%|██████████| 543/543 [02:16<00:00,  3.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.81it/s]


                   all        648       1520       0.82      0.809       0.85      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     53/200      3.32G     0.8032     0.9918      1.385         10        768: 100%|██████████| 543/543 [02:13<00:00,  4.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.87it/s]

                   all        648       1520       0.81      0.795       0.85      0.657



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     54/200      3.31G     0.7905      0.946      1.367         21        768: 100%|██████████| 543/543 [02:15<00:00,  4.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.88it/s]

                   all        648       1520      0.797      0.806      0.849      0.648



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     55/200      3.34G     0.7906     0.9679      1.365          7        768: 100%|██████████| 543/543 [02:15<00:00,  4.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:14<00:00,  5.78it/s]


                   all        648       1520      0.792      0.782      0.849      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     56/200      3.35G     0.7868     0.9489      1.363         12        768: 100%|██████████| 543/543 [02:14<00:00,  4.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.93it/s]

                   all        648       1520      0.808       0.77      0.834      0.646



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     57/200      3.33G     0.7838     0.9481      1.369          7        768: 100%|██████████| 543/543 [02:13<00:00,  4.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  6.03it/s]

                   all        648       1520      0.801        0.8      0.855      0.659



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     58/200      3.33G     0.7905     0.9775      1.375         12        768: 100%|██████████| 543/543 [02:14<00:00,  4.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.93it/s]

                   all        648       1520      0.812      0.769      0.849      0.658



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     59/200      3.33G     0.7731     0.9394      1.349          6        768: 100%|██████████| 543/543 [02:13<00:00,  4.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.81it/s]

                   all        648       1520       0.83      0.775      0.847       0.66



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     60/200      3.32G     0.7844      0.944      1.361          5        768: 100%|██████████| 543/543 [02:13<00:00,  4.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.93it/s]

                   all        648       1520      0.823      0.778      0.849      0.652



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     61/200      3.33G     0.7711     0.8909      1.351          9        768: 100%|██████████| 543/543 [02:13<00:00,  4.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.87it/s]

                   all        648       1520       0.83      0.792      0.856      0.662



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     62/200      3.31G     0.7777     0.9229      1.347          6        768: 100%|██████████| 543/543 [02:14<00:00,  4.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  6.05it/s]

                   all        648       1520      0.843      0.791      0.857      0.665



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     63/200      3.32G     0.7751      0.923      1.357          4        768: 100%|██████████| 543/543 [02:12<00:00,  4.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.99it/s]


                   all        648       1520      0.779      0.819      0.847      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     64/200      3.32G     0.7709     0.8824      1.351          4        768: 100%|██████████| 543/543 [02:14<00:00,  4.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.83it/s]

                   all        648       1520      0.809      0.768      0.839      0.646



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     65/200      3.33G     0.7598     0.8991      1.333         17        768: 100%|██████████| 543/543 [02:10<00:00,  4.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.80it/s]

                   all        648       1520      0.816      0.804      0.857      0.666



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     66/200      3.32G     0.7578     0.8588      1.337          7        768: 100%|██████████| 543/543 [01:23<00:00,  6.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.63it/s]

                   all        648       1520      0.853      0.778      0.847      0.646



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     67/200      3.32G      0.752     0.8388       1.32         10        768: 100%|██████████| 543/543 [01:22<00:00,  6.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.87it/s]


                   all        648       1520      0.826      0.774      0.842      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     68/200      3.32G     0.7424     0.8414      1.324         12        768: 100%|██████████| 543/543 [01:20<00:00,  6.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.56it/s]

                   all        648       1520      0.828      0.796      0.847      0.662



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     69/200      3.31G     0.7524     0.8378       1.33         21        768: 100%|██████████| 543/543 [01:19<00:00,  6.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.67it/s]

                   all        648       1520      0.839      0.829       0.87      0.672



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     70/200      3.31G     0.7414     0.8217      1.323          3        768: 100%|██████████| 543/543 [01:18<00:00,  6.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.64it/s]


                   all        648       1520      0.829      0.809      0.861      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     71/200      3.33G     0.7281     0.8023      1.304          4        768: 100%|██████████| 543/543 [01:18<00:00,  6.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.75it/s]


                   all        648       1520      0.846      0.815      0.867      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     72/200      3.36G     0.7211     0.8028      1.306         18        768: 100%|██████████| 543/543 [01:18<00:00,  6.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.38it/s]

                   all        648       1520      0.832       0.81      0.847      0.656



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     73/200      3.33G     0.7224     0.7612      1.301          7        768: 100%|██████████| 543/543 [01:18<00:00,  6.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.56it/s]

                   all        648       1520      0.847      0.802      0.849      0.657



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     74/200      3.32G     0.7221     0.7953      1.297          7        768: 100%|██████████| 543/543 [01:18<00:00,  6.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.46it/s]

                   all        648       1520      0.833      0.805      0.846      0.648



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     75/200      3.32G     0.7433     0.8276       1.32         30        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.65it/s]

                   all        648       1520      0.827      0.819      0.861      0.674



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     76/200      3.32G     0.7177     0.7866        1.3         22        768: 100%|██████████| 543/543 [01:18<00:00,  6.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.52it/s]

                   all        648       1520      0.844      0.808      0.862      0.671



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     77/200      3.32G     0.7266     0.8033      1.303         29        768: 100%|██████████| 543/543 [01:18<00:00,  6.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.57it/s]

                   all        648       1520       0.84       0.83      0.865      0.674



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     78/200      3.32G     0.7087     0.7603      1.289          6        768: 100%|██████████| 543/543 [01:18<00:00,  6.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.55it/s]


                   all        648       1520      0.861      0.817      0.878      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     79/200      3.32G     0.7283     0.7957      1.296         13        768: 100%|██████████| 543/543 [01:18<00:00,  6.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.70it/s]

                   all        648       1520      0.871      0.808      0.873      0.687



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     80/200      3.32G     0.7161      0.785      1.301         12        768: 100%|██████████| 543/543 [01:18<00:00,  6.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.72it/s]

                   all        648       1520      0.835      0.819      0.868      0.684



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     81/200      3.33G     0.7121     0.7806      1.289         19        768: 100%|██████████| 543/543 [01:17<00:00,  6.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.55it/s]

                   all        648       1520      0.864      0.802      0.869      0.685



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     82/200      3.31G     0.7082     0.7749      1.285          4        768: 100%|██████████| 543/543 [01:18<00:00,  6.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.61it/s]

                   all        648       1520       0.85      0.798      0.863      0.682



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     83/200      3.32G     0.7044     0.7626      1.282          3        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.77it/s]

                   all        648       1520      0.871      0.815      0.874      0.691



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     84/200      3.32G     0.6883     0.7201      1.264         10        768: 100%|██████████| 543/543 [01:18<00:00,  6.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.53it/s]

                   all        648       1520      0.849      0.824      0.867      0.683



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     85/200      3.32G     0.7083     0.7495      1.284          5        768: 100%|██████████| 543/543 [01:17<00:00,  6.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.65it/s]

                   all        648       1520      0.833      0.842      0.875      0.693



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     86/200      3.32G     0.7027     0.7623      1.276          3        768: 100%|██████████| 543/543 [01:19<00:00,  6.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.34it/s]


                   all        648       1520      0.848      0.812      0.873       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     87/200      3.34G     0.7115     0.7591      1.282          3        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.80it/s]

                   all        648       1520      0.856       0.82      0.869      0.685



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     88/200      3.35G     0.6809     0.7178      1.247          8        768: 100%|██████████| 543/543 [01:19<00:00,  6.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.49it/s]

                   all        648       1520      0.868      0.816      0.879      0.696



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     89/200      3.32G     0.6785       0.72      1.257         12        768: 100%|██████████| 543/543 [01:21<00:00,  6.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.36it/s]

                   all        648       1520       0.84      0.836      0.877      0.689



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     90/200      3.32G     0.6666     0.6664      1.239         20        768: 100%|██████████| 543/543 [01:19<00:00,  6.85it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.53it/s]

                   all        648       1520      0.832       0.84      0.873      0.683



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     91/200      3.32G     0.6949     0.7209      1.278          5        768: 100%|██████████| 543/543 [01:20<00:00,  6.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.08it/s]

                   all        648       1520      0.821      0.846      0.862      0.685



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     92/200      3.32G     0.6807     0.7144       1.25          5        768: 100%|██████████| 543/543 [01:20<00:00,  6.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.49it/s]

                   all        648       1520      0.854      0.832      0.878        0.7



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     93/200      3.32G     0.6706     0.6622      1.245          8        768: 100%|██████████| 543/543 [01:19<00:00,  6.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.60it/s]

                   all        648       1520      0.859       0.82      0.874      0.693



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     94/200      3.32G     0.6819     0.7074      1.262         12        768: 100%|██████████| 543/543 [01:19<00:00,  6.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.60it/s]

                   all        648       1520      0.874      0.819      0.878      0.695



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     95/200      3.33G     0.6644     0.6833       1.24          8        768: 100%|██████████| 543/543 [01:21<00:00,  6.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.61it/s]

                   all        648       1520      0.848      0.827      0.868      0.686



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     96/200      3.32G     0.6756     0.6993      1.262          3        768: 100%|██████████| 543/543 [01:19<00:00,  6.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.86it/s]


                   all        648       1520      0.836      0.832      0.876      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     97/200      3.31G     0.6552     0.6636       1.23         20        768: 100%|██████████| 543/543 [01:19<00:00,  6.85it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.71it/s]

                   all        648       1520      0.851      0.822      0.873      0.696



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     98/200      3.32G      0.648     0.6564      1.223         13        768: 100%|██████████| 543/543 [01:17<00:00,  7.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.88it/s]

                   all        648       1520      0.825      0.851      0.879      0.702



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     99/200      3.32G      0.649     0.6555      1.234          4        768: 100%|██████████| 543/543 [01:17<00:00,  7.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.79it/s]

                   all        648       1520      0.861      0.808      0.861      0.682



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    100/200      3.32G     0.6456     0.6523      1.221          7        768: 100%|██████████| 543/543 [01:17<00:00,  6.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.87it/s]

                   all        648       1520      0.852      0.831      0.874      0.689



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    101/200      3.32G      0.639     0.6531      1.212          4        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.77it/s]

                   all        648       1520      0.825      0.833       0.87      0.692



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    102/200      3.31G     0.6466     0.6367      1.217          7        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.93it/s]

                   all        648       1520      0.863      0.835      0.879      0.697



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    103/200      3.35G     0.6434     0.6344       1.22         12        768: 100%|██████████| 543/543 [01:19<00:00,  6.85it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.73it/s]

                   all        648       1520      0.852      0.838      0.872      0.697



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    104/200      3.36G     0.6316     0.6299      1.213         13        768: 100%|██████████| 543/543 [01:19<00:00,  6.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.73it/s]

                   all        648       1520      0.862      0.828      0.877      0.707



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    105/200      3.33G     0.6324     0.6279      1.204         10        768: 100%|██████████| 543/543 [01:22<00:00,  6.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.78it/s]

                   all        648       1520      0.839      0.838      0.874      0.701



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    106/200      3.32G     0.6162     0.5891      1.193          6        768: 100%|██████████| 543/543 [01:20<00:00,  6.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.65it/s]

                   all        648       1520      0.869      0.822      0.878      0.706



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    107/200      3.32G     0.6226     0.6058      1.202         13        768: 100%|██████████| 543/543 [01:19<00:00,  6.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.51it/s]

                   all        648       1520      0.853      0.835      0.876        0.7



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    108/200      3.33G     0.6248      0.605      1.199          7        768: 100%|██████████| 543/543 [01:18<00:00,  6.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.60it/s]

                   all        648       1520      0.875      0.816       0.88      0.708



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    109/200      3.32G     0.6139      0.591        1.2          6        768: 100%|██████████| 543/543 [01:36<00:00,  5.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.99it/s]

                   all        648       1520      0.834      0.851      0.877      0.697



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    110/200      3.33G     0.5907     0.5771      1.176          4        768: 100%|██████████| 543/543 [01:21<00:00,  6.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.78it/s]

                   all        648       1520      0.875      0.815      0.879      0.705



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    111/200      3.32G     0.6217     0.6054       1.19          3        768: 100%|██████████| 543/543 [01:19<00:00,  6.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.80it/s]

                   all        648       1520      0.866      0.824      0.879        0.7



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    112/200      3.33G     0.6127     0.5728      1.187          4        768: 100%|██████████| 543/543 [01:18<00:00,  6.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.00it/s]

                   all        648       1520      0.864      0.825      0.876      0.699



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    113/200      3.33G     0.6114     0.5703       1.18          9        768: 100%|██████████| 543/543 [01:18<00:00,  6.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.75it/s]

                   all        648       1520      0.864      0.842       0.88      0.707



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    114/200      3.32G       0.61     0.5944      1.186          3        768: 100%|██████████| 543/543 [01:18<00:00,  6.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.89it/s]

                   all        648       1520      0.846      0.851      0.879      0.702



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    115/200      3.33G     0.6218     0.5987      1.187          9        768: 100%|██████████| 543/543 [01:18<00:00,  6.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.86it/s]

                   all        648       1520      0.853      0.836      0.877      0.701



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    116/200      3.32G      0.601     0.5639      1.175          5        768: 100%|██████████| 543/543 [01:18<00:00,  6.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.84it/s]

                   all        648       1520      0.863      0.837      0.875      0.704



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    117/200      3.32G     0.6059     0.5774      1.179          5        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.39it/s]

                   all        648       1520      0.865      0.815      0.877      0.709



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    118/200      3.31G     0.5905     0.5662      1.163         10        768: 100%|██████████| 543/543 [01:18<00:00,  6.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.95it/s]


                   all        648       1520      0.864      0.828      0.879      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    119/200      3.33G     0.6044     0.5707      1.179          7        768: 100%|██████████| 543/543 [01:17<00:00,  7.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.85it/s]

                   all        648       1520       0.84      0.833      0.871      0.697



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    120/200      3.35G     0.5842     0.5403      1.152         12        768: 100%|██████████| 543/543 [01:17<00:00,  6.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.79it/s]

                   all        648       1520      0.857      0.842      0.882      0.716



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    121/200      3.33G      0.587     0.5468      1.169          7        768: 100%|██████████| 543/543 [01:18<00:00,  6.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.71it/s]


                   all        648       1520      0.856      0.848      0.886      0.718

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    122/200      3.33G     0.5845     0.5479      1.168          7        768: 100%|██████████| 543/543 [01:17<00:00,  6.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.95it/s]

                   all        648       1520      0.856      0.836      0.884      0.708



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    123/200      3.32G     0.5852      0.551       1.16         11        768: 100%|██████████| 543/543 [01:18<00:00,  6.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.91it/s]


                   all        648       1520      0.871      0.841      0.887      0.712

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    124/200      3.33G     0.5892     0.5703      1.158          9        768: 100%|██████████| 543/543 [01:18<00:00,  6.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.95it/s]

                   all        648       1520      0.856      0.836      0.883      0.717



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    125/200      3.32G     0.5752     0.5535      1.162         11        768: 100%|██████████| 543/543 [01:23<00:00,  6.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.71it/s]


                   all        648       1520      0.883      0.846      0.889      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    126/200      3.33G     0.5667     0.5174      1.146          9        768: 100%|██████████| 543/543 [01:18<00:00,  6.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.08it/s]


                   all        648       1520      0.858      0.852      0.887      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    127/200      3.32G     0.5926     0.5567       1.17          9        768: 100%|██████████| 543/543 [01:18<00:00,  6.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.87it/s]

                   all        648       1520      0.854      0.836      0.879      0.717



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    128/200      3.31G     0.5905     0.5785      1.165          3        768: 100%|██████████| 543/543 [01:19<00:00,  6.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.22it/s]

                   all        648       1520      0.852      0.825      0.875      0.715



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    129/200      3.32G     0.5726     0.5362      1.146          5        768: 100%|██████████| 543/543 [01:17<00:00,  6.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.51it/s]

                   all        648       1520      0.876       0.82      0.879      0.714



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    130/200      3.32G     0.5775     0.5488      1.154          7        768: 100%|██████████| 543/543 [01:19<00:00,  6.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.98it/s]

                   all        648       1520      0.867      0.838      0.889      0.723



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    131/200      3.32G       0.57     0.5294      1.148          3        768: 100%|██████████| 543/543 [01:42<00:00,  5.31it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  6.07it/s]

                   all        648       1520      0.878      0.824      0.887      0.727



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    132/200      3.32G     0.5583     0.5102      1.132         12        768: 100%|██████████| 543/543 [02:12<00:00,  4.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  6.02it/s]

                   all        648       1520      0.873       0.83      0.892      0.733



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    133/200      3.33G      0.558     0.4987      1.136          4        768: 100%|██████████| 543/543 [02:12<00:00,  4.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  6.10it/s]

                   all        648       1520      0.873       0.84      0.888      0.726



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    134/200       3.3G     0.5506     0.4967      1.136         18        768: 100%|██████████| 543/543 [02:12<00:00,  4.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  6.12it/s]

                   all        648       1520      0.877      0.823      0.885      0.723



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    135/200      3.32G     0.5603     0.5023      1.138          6        768: 100%|██████████| 543/543 [02:13<00:00,  4.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.86it/s]


                   all        648       1520      0.872      0.835      0.882      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    136/200      3.35G     0.5553     0.5045      1.139          4        768: 100%|██████████| 543/543 [02:15<00:00,  4.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.98it/s]

                   all        648       1520       0.86      0.837      0.883      0.721



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    137/200      3.33G      0.548     0.4914      1.126          3        768: 100%|██████████| 543/543 [02:14<00:00,  4.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.84it/s]

                   all        648       1520       0.87      0.828      0.881      0.723



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    138/200      3.33G     0.5508     0.5147      1.135          6        768: 100%|██████████| 543/543 [02:14<00:00,  4.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.82it/s]

                   all        648       1520      0.871      0.837      0.883      0.724



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    139/200      3.33G     0.5493     0.5023       1.12          4        768: 100%|██████████| 543/543 [02:14<00:00,  4.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:13<00:00,  5.93it/s]

                   all        648       1520      0.874      0.852      0.884      0.725



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    140/200      3.33G     0.5409     0.4875      1.128         13        768: 100%|██████████| 543/543 [02:14<00:00,  4.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:14<00:00,  5.78it/s]

                   all        648       1520      0.878       0.83      0.891      0.725



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    141/200      3.32G     0.5383      0.484      1.123         20        768: 100%|██████████| 543/543 [01:38<00:00,  5.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.65it/s]

                   all        648       1520       0.86      0.842      0.887      0.727



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    142/200      3.32G     0.5295     0.4823      1.107          4        768: 100%|██████████| 543/543 [01:20<00:00,  6.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.12it/s]

                   all        648       1520      0.876      0.826      0.887      0.729



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    143/200      3.31G     0.5351     0.4815       1.12         15        768: 100%|██████████| 543/543 [01:24<00:00,  6.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.57it/s]

                   all        648       1520      0.851      0.849      0.884      0.727


PermissionError: [Errno 13] Permission denied: 'indonesian_food_yolov8\\yolov8m_balance_run\\results.csv'

In [1]:
from ultralytics import YOLO
import torch

# --- KONFIGURASI PATH ---
DATA_YAML_PATH = r"C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\data.yaml"

# PATH UNTUK LANJUTKAN DARI CHECKPOINT TERAKHIR
# Asumsikan checkpoint terakhir yang valid ada di folder run Anda
LAST_CHECKPOINT = "indonesian_food_yolov8/yolov8m_balance_run/weights/last.pt" 

# Muat model dari checkpoint terakhir)
model = YOLO(LAST_CHECKPOINT)

# GPU / CPU
device = 0 if torch.cuda.is_available() else "cpu"
print("Training dilanjutkan pada:", device)

train_results = model.train(
    data=DATA_YAML_PATH,
    epochs=200,             
    patience=30,            
    imgsz=768,              
    batch=4, 
    device=device,

    # 🔥 OPTIMASI UTAMA (Mencegah Collapse)
    optimizer="AdamW",
    lr0=0.0005,             # DITURUNKAN DARI 0.001 MENJADI 0.0005
    cos_lr=True,
    warmup_epochs=5,
    weight_decay=0.0005,

    # 🔥 AUGMENTASI (Disesuaikan agar tidak terlalu agresif)
    hsv_h=0.012, hsv_s=0.6, hsv_v=0.35,
    degrees=4, translate=0.10, scale=0.40, shear=0.05, perspective=0.0,
    fliplr=0.5, flipud=0.15, 
    mosaic=0.10,            # DITURUNKAN DARI 0.20
    mixup=0.05, 
    erasing=0.10,           # DITURUNKAN DARI 0.25

    multi_scale=False,

    # 🔥 Logging
    project="indonesian_food_yolov8",
    name="yolov8m_final_rerun", # Ganti nama folder untuk run baru
    exist_ok=True,
)

Training dilanjutkan pada: 0
New https://pypi.org/project/ultralytics/8.3.231 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.74  Python-3.10.11 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB)
engine\trainer: task=detect, mode=train, model=indonesian_food_yolov8/yolov8m_balance_run/weights/last.pt, data=C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\data.yaml, epochs=200, time=None, patience=30, batch=4, imgsz=768, save=True, save_period=-1, cache=False, device=0, workers=8, project=indonesian_food_yolov8, name=yolov8m_final_rerun, exist_ok=True, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybri

train: Scanning C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\train\labels.cache... 2171 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2171/2171 [00:00<?, ?it/s]

WARNING  Box and segment counts should be equal, but got len(segments) = 3235, len(boxes) = 4467. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.



val: Scanning C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\valid\labels.cache... 648 images, 0 backgrounds, 0 corrupt: 100%|██████████| 648/648 [00:00<?, ?it/s]

WARNING  Box and segment counts should be equal, but got len(segments) = 1100, len(boxes) = 1520. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.


Plotting labels to indonesian_food_yolov8\yolov8m_final_rerun\labels.jpg... 
optimizer: AdamW(lr=0.0005, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 768 train, 768 val
Using 8 dataloader workers
Logging results to indonesian_food_yolov8\yolov8m_final_rerun
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      1/200      2.79G     0.6875     0.8037      1.279          6        768: 100%|██████████| 543/543 [01:22<00:00,  6.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.68it/s]

                   all        648       1520      0.788      0.799      0.843      0.671



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      2/200       2.8G     0.6112     0.6153      1.189         14        768: 100%|██████████| 543/543 [01:20<00:00,  6.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:07<00:00, 10.19it/s]


                   all        648       1520       0.82      0.802      0.843      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      3/200      2.77G     0.5747     0.5701      1.149          3        768: 100%|██████████| 543/543 [01:18<00:00,  6.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.04it/s]

                   all        648       1520      0.829      0.836      0.867      0.701



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      4/200      2.76G     0.5567     0.5399      1.138         12        768: 100%|██████████| 543/543 [01:17<00:00,  7.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.92it/s]

                   all        648       1520      0.849      0.837      0.881      0.707



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      5/200      2.76G     0.5609     0.5276      1.147          7        768: 100%|██████████| 543/543 [01:18<00:00,  6.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.79it/s]

                   all        648       1520      0.867      0.821      0.877      0.701



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      6/200      2.75G     0.5775     0.5474      1.159          6        768: 100%|██████████| 543/543 [01:21<00:00,  6.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.44it/s]

                   all        648       1520      0.838      0.829      0.866      0.702



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      7/200      2.75G     0.5561     0.5391      1.145          5        768: 100%|██████████| 543/543 [01:20<00:00,  6.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.58it/s]

                   all        648       1520      0.838      0.828      0.871      0.707



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      8/200       2.8G     0.5619     0.5215      1.145          3        768: 100%|██████████| 543/543 [01:19<00:00,  6.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.58it/s]

                   all        648       1520      0.864      0.804      0.874      0.705



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      9/200      2.77G     0.5641     0.5329      1.151         12        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:07<00:00, 10.27it/s]

                   all        648       1520      0.827      0.842       0.87      0.703



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     10/200      2.76G     0.5677     0.5222      1.155         10        768: 100%|██████████| 543/543 [01:19<00:00,  6.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.93it/s]

                   all        648       1520      0.855      0.833      0.874      0.704



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     11/200      2.76G     0.5775     0.5711      1.168          3        768: 100%|██████████| 543/543 [01:17<00:00,  6.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.02it/s]

                   all        648       1520      0.875      0.826      0.881      0.719



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     12/200      2.76G     0.5543     0.5214      1.142          4        768: 100%|██████████| 543/543 [01:17<00:00,  6.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.65it/s]

                   all        648       1520      0.836      0.817      0.873      0.712



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     13/200      2.77G     0.5594     0.5228       1.15          7        768: 100%|██████████| 543/543 [01:19<00:00,  6.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.39it/s]

                   all        648       1520      0.839      0.838      0.873      0.708



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     14/200      2.76G     0.5591     0.5215      1.144          9        768: 100%|██████████| 543/543 [01:22<00:00,  6.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.21it/s]

                   all        648       1520      0.874       0.83      0.876      0.709



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     15/200      2.76G     0.5589     0.5221      1.144         15        768: 100%|██████████| 543/543 [01:21<00:00,  6.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.44it/s]


                   all        648       1520      0.842      0.821      0.867      0.707

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     16/200      2.76G      0.562     0.5435      1.147          5        768: 100%|██████████| 543/543 [01:23<00:00,  6.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.67it/s]

                   all        648       1520      0.844      0.854      0.873      0.708



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     17/200      2.76G     0.5441     0.5173      1.132         10        768: 100%|██████████| 543/543 [01:20<00:00,  6.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.42it/s]


                   all        648       1520      0.855      0.824      0.874      0.714

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     18/200      2.76G     0.5469     0.5013      1.138          4        768: 100%|██████████| 543/543 [01:19<00:00,  6.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.78it/s]


                   all        648       1520      0.853      0.824      0.874      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     19/200      2.76G     0.5609     0.5163      1.154          3        768: 100%|██████████| 543/543 [01:21<00:00,  6.67it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.93it/s]

                   all        648       1520      0.851      0.853      0.879      0.723



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     20/200      2.75G     0.5563     0.5117      1.137          8        768: 100%|██████████| 543/543 [01:21<00:00,  6.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.30it/s]

                   all        648       1520      0.827       0.83      0.863      0.703



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     21/200      2.75G     0.5496     0.5283      1.137         10        768: 100%|██████████| 543/543 [01:20<00:00,  6.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.28it/s]

                   all        648       1520      0.857      0.829      0.864      0.707



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     22/200      2.75G     0.5387     0.5115      1.128         10        768: 100%|██████████| 543/543 [01:22<00:00,  6.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.28it/s]

                   all        648       1520      0.858      0.822      0.876      0.721



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     23/200      2.75G     0.5327      0.493      1.119          3        768: 100%|██████████| 543/543 [01:23<00:00,  6.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.63it/s]

                   all        648       1520      0.867      0.818      0.877      0.725



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     24/200       2.8G     0.5532     0.5142      1.142          4        768: 100%|██████████| 543/543 [01:22<00:00,  6.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.14it/s]

                   all        648       1520      0.862      0.827      0.873      0.719



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     25/200      2.76G     0.5544     0.5196      1.139          7        768: 100%|██████████| 543/543 [01:25<00:00,  6.35it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.76it/s]

                   all        648       1520      0.859       0.83      0.878      0.723



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     26/200      2.76G     0.5589     0.5309      1.137          4        768: 100%|██████████| 543/543 [01:26<00:00,  6.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.02it/s]

                   all        648       1520      0.854      0.833      0.867      0.709



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     27/200      2.76G     0.5315     0.4976      1.122          5        768: 100%|██████████| 543/543 [01:22<00:00,  6.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.45it/s]


                   all        648       1520      0.842      0.819      0.867      0.695

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     28/200      2.75G     0.5614     0.5205      1.137          3        768: 100%|██████████| 543/543 [01:22<00:00,  6.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.01it/s]

                   all        648       1520      0.864      0.808      0.869      0.698



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     29/200      2.76G     0.5307      0.491       1.12          5        768: 100%|██████████| 543/543 [01:25<00:00,  6.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:09<00:00,  8.62it/s]

                   all        648       1520      0.848      0.829      0.871      0.715



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     30/200      2.76G     0.5361     0.4907      1.123          4        768: 100%|██████████| 543/543 [01:23<00:00,  6.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.25it/s]

                   all        648       1520       0.85       0.83       0.87      0.724



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     31/200      2.75G     0.5407     0.4962      1.128          3        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.04it/s]


                   all        648       1520      0.846      0.834      0.872      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     32/200      2.75G     0.5228     0.4742       1.11         31        768: 100%|██████████| 543/543 [01:16<00:00,  7.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.90it/s]

                   all        648       1520      0.835      0.833       0.87      0.712



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     33/200      2.76G     0.5457     0.5153      1.133          5        768: 100%|██████████| 543/543 [01:16<00:00,  7.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.98it/s]

                   all        648       1520      0.835      0.842      0.872      0.715



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     34/200      2.76G     0.5316      0.493      1.118          4        768: 100%|██████████| 543/543 [01:16<00:00,  7.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.89it/s]

                   all        648       1520      0.852      0.832      0.872      0.717



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     35/200      2.76G     0.5317     0.4889      1.123         11        768: 100%|██████████| 543/543 [01:17<00:00,  7.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.04it/s]

                   all        648       1520      0.846      0.848      0.868      0.706



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     36/200      2.76G     0.5279     0.4775      1.121          3        768: 100%|██████████| 543/543 [01:15<00:00,  7.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.01it/s]


                   all        648       1520      0.852      0.845      0.876      0.721

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     37/200      2.75G     0.5248     0.4908       1.11          7        768: 100%|██████████| 543/543 [01:15<00:00,  7.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.06it/s]

                   all        648       1520      0.864      0.806      0.868      0.713



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     38/200      2.75G     0.5274     0.4945      1.118          8        768: 100%|██████████| 543/543 [01:15<00:00,  7.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.62it/s]

                   all        648       1520      0.866      0.796      0.868      0.713



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     39/200      2.76G     0.5151     0.4691      1.104          6        768: 100%|██████████| 543/543 [01:18<00:00,  6.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.08it/s]

                   all        648       1520      0.838      0.828      0.865      0.718



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     40/200       2.8G     0.5156     0.4783      1.109         14        768: 100%|██████████| 543/543 [01:16<00:00,  7.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.06it/s]

                   all        648       1520      0.842      0.822      0.864       0.71



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     41/200      2.77G     0.5202     0.4699      1.109          5        768: 100%|██████████| 543/543 [01:16<00:00,  7.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.86it/s]

                   all        648       1520      0.825      0.828      0.854      0.699



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     42/200      2.76G     0.5117     0.4804      1.108          3        768: 100%|██████████| 543/543 [01:15<00:00,  7.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.90it/s]


                   all        648       1520      0.848      0.817      0.864      0.711

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     43/200      2.76G     0.5079     0.4615      1.093          6        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.95it/s]


                   all        648       1520      0.821      0.829      0.855      0.701

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     44/200      2.76G     0.5111     0.4656      1.101          5        768: 100%|██████████| 543/543 [01:16<00:00,  7.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.78it/s]

                   all        648       1520      0.857      0.824      0.871      0.719



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     45/200      2.77G     0.5174     0.4745       1.11          5        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.73it/s]

                   all        648       1520      0.865      0.803      0.865      0.715



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     46/200      2.75G     0.5092     0.4665       1.11         15        768: 100%|██████████| 543/543 [01:17<00:00,  7.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.00it/s]

                   all        648       1520      0.833      0.815      0.864      0.711



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     47/200      2.76G     0.5079       0.47        1.1         11        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.10it/s]


                   all        648       1520      0.837      0.831      0.867      0.719

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     48/200      2.75G     0.5265     0.4819      1.119          5        768: 100%|██████████| 543/543 [01:16<00:00,  7.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.92it/s]

                   all        648       1520      0.873      0.813      0.874      0.726



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     49/200      2.76G      0.498     0.4427      1.086          3        768: 100%|██████████| 543/543 [01:16<00:00,  7.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.06it/s]

                   all        648       1520       0.86      0.806      0.869       0.72



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     50/200      2.75G     0.5128     0.4647       1.11          3        768: 100%|██████████| 543/543 [01:16<00:00,  7.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.87it/s]

                   all        648       1520      0.866      0.816      0.872      0.724



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     51/200      2.75G     0.5035     0.4516      1.084          5        768: 100%|██████████| 543/543 [01:16<00:00,  7.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.83it/s]

                   all        648       1520      0.851      0.837      0.877      0.726



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     52/200      2.75G     0.5124     0.4541      1.092          4        768: 100%|██████████| 543/543 [01:16<00:00,  7.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.84it/s]

                   all        648       1520      0.857      0.823       0.87       0.72



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     53/200      2.76G     0.4851       0.44      1.077          6        768: 100%|██████████| 543/543 [01:16<00:00,  7.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.00it/s]

                   all        648       1520       0.84      0.823      0.872      0.725



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     54/200      2.74G     0.5023     0.4418      1.093         22        768: 100%|██████████| 543/543 [01:20<00:00,  6.77it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.88it/s]

                   all        648       1520      0.841      0.857      0.875      0.727



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     55/200      2.82G     0.4909     0.4364      1.085          4        768: 100%|██████████| 543/543 [01:16<00:00,  7.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.07it/s]

                   all        648       1520      0.891      0.815      0.882      0.722



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     56/200      2.81G     0.4991     0.4459       1.09         11        768: 100%|██████████| 543/543 [01:15<00:00,  7.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.12it/s]

                   all        648       1520      0.852      0.841       0.88      0.727



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     57/200      2.76G     0.4924     0.4455      1.078          8        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.99it/s]


                   all        648       1520      0.863      0.831      0.875      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     58/200      2.77G     0.4985     0.4545      1.091          9        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.84it/s]

                   all        648       1520      0.883      0.827      0.883       0.73



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     59/200      2.75G     0.5022     0.4521       1.09          6        768: 100%|██████████| 543/543 [01:18<00:00,  6.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.86it/s]

                   all        648       1520      0.863      0.843      0.882      0.727



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     60/200      2.75G     0.4887     0.4418      1.084          3        768: 100%|██████████| 543/543 [01:16<00:00,  7.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.90it/s]

                   all        648       1520      0.853      0.853      0.875      0.725



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     61/200      2.75G     0.4999     0.4395      1.085         11        768: 100%|██████████| 543/543 [01:17<00:00,  7.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.81it/s]


                   all        648       1520      0.873       0.83      0.871      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     62/200      2.76G     0.4924     0.4369      1.079          6        768: 100%|██████████| 543/543 [01:16<00:00,  7.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.01it/s]

                   all        648       1520       0.87      0.837      0.877      0.726



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     63/200      2.76G     0.4964     0.4363      1.079          4        768: 100%|██████████| 543/543 [01:16<00:00,  7.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.90it/s]

                   all        648       1520      0.856      0.844      0.879      0.726



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     64/200      2.77G     0.4867     0.4204       1.08          9        768: 100%|██████████| 543/543 [01:15<00:00,  7.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.10it/s]

                   all        648       1520      0.853      0.844       0.88      0.728



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     65/200      2.75G     0.5021     0.4392      1.097         11        768: 100%|██████████| 543/543 [01:16<00:00,  7.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.99it/s]

                   all        648       1520      0.855      0.841      0.882      0.729



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     66/200      2.76G      0.496     0.4356      1.087          6        768: 100%|██████████| 543/543 [01:16<00:00,  7.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.73it/s]

                   all        648       1520      0.888      0.814      0.874      0.722



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     67/200      2.76G     0.4907     0.4654      1.091          6        768: 100%|██████████| 543/543 [01:17<00:00,  7.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.82it/s]

                   all        648       1520      0.847       0.83      0.877      0.729



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     68/200      2.75G     0.4707     0.4126      1.056          9        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.10it/s]

                   all        648       1520      0.848      0.827      0.878      0.724



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     69/200      2.75G     0.4846     0.4341       1.08          8        768: 100%|██████████| 543/543 [01:16<00:00,  7.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.87it/s]

                   all        648       1520      0.842      0.843      0.876      0.727



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     70/200      2.75G     0.4851     0.4322      1.078          3        768: 100%|██████████| 543/543 [01:16<00:00,  7.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.01it/s]

                   all        648       1520      0.866      0.795      0.873      0.724



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     71/200      2.76G     0.4861     0.4318      1.076          7        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.66it/s]

                   all        648       1520      0.868      0.822      0.879      0.725



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     72/200      2.79G     0.4823     0.4422       1.08         16        768: 100%|██████████| 543/543 [01:16<00:00,  7.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.79it/s]


                   all        648       1520      0.862      0.819      0.869      0.715

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     73/200      2.77G     0.4759      0.419      1.069          3        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.87it/s]

                   all        648       1520      0.858      0.833       0.87      0.723



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     74/200      2.76G     0.4705     0.4073      1.057          7        768: 100%|██████████| 543/543 [01:16<00:00,  7.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.77it/s]

                   all        648       1520      0.856      0.825      0.871      0.724



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     75/200      2.75G     0.4775     0.4081      1.067         26        768: 100%|██████████| 543/543 [01:16<00:00,  7.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.81it/s]

                   all        648       1520      0.872      0.833      0.879      0.726



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     76/200      2.75G     0.4741     0.4304       1.07         15        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.00it/s]


                   all        648       1520      0.847      0.852      0.877      0.728

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     77/200      2.76G       0.46     0.3989      1.056         14        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.83it/s]


                   all        648       1520      0.844      0.848      0.878      0.728

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     78/200      2.76G     0.4861      0.435      1.083          3        768: 100%|██████████| 543/543 [01:17<00:00,  7.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:07<00:00, 10.13it/s]

                   all        648       1520      0.838      0.842      0.876       0.73



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     79/200      2.75G     0.4792     0.4353      1.069         12        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.91it/s]

                   all        648       1520      0.861      0.807      0.871       0.72



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     80/200      2.76G     0.4745     0.4297      1.066         14        768: 100%|██████████| 543/543 [01:16<00:00,  7.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.80it/s]

                   all        648       1520      0.853      0.847      0.881      0.731



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     81/200      2.76G     0.4747     0.4217      1.062          9        768: 100%|██████████| 543/543 [01:16<00:00,  7.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.03it/s]

                   all        648       1520      0.846      0.858      0.881      0.729



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     82/200      2.76G     0.4773     0.4103      1.062          6        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.79it/s]

                   all        648       1520      0.857      0.829      0.879      0.729



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     83/200      2.76G     0.4472     0.3976      1.047          3        768: 100%|██████████| 543/543 [01:16<00:00,  7.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.86it/s]

                   all        648       1520      0.877      0.815      0.879      0.732



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     84/200      2.75G      0.477     0.4266      1.077          7        768: 100%|██████████| 543/543 [01:16<00:00,  7.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.91it/s]


                   all        648       1520      0.859      0.816      0.873      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     85/200      2.77G      0.454     0.4008      1.048         10        768: 100%|██████████| 543/543 [01:16<00:00,  7.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.82it/s]

                   all        648       1520      0.878      0.848      0.886       0.74



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     86/200      2.74G     0.4651     0.3964      1.059          3        768: 100%|██████████| 543/543 [01:16<00:00,  7.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.58it/s]

                   all        648       1520      0.828       0.84      0.868      0.725



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     87/200      2.76G     0.4461      0.393      1.042          7        768: 100%|██████████| 543/543 [01:16<00:00,  7.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.69it/s]


                   all        648       1520      0.842      0.843      0.872      0.729

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     88/200       2.8G     0.4588     0.4063      1.052         10        768: 100%|██████████| 543/543 [01:16<00:00,  7.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.74it/s]

                   all        648       1520      0.865      0.831      0.876      0.731



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     89/200      2.76G     0.4467     0.3926      1.045          4        768: 100%|██████████| 543/543 [01:16<00:00,  7.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.84it/s]


                   all        648       1520      0.849       0.84      0.867      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     90/200      2.76G     0.4547     0.4009      1.053          4        768: 100%|██████████| 543/543 [01:18<00:00,  6.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.90it/s]


                   all        648       1520      0.872      0.825      0.876      0.734

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     91/200      2.76G     0.4526     0.3838      1.051          5        768: 100%|██████████| 543/543 [01:17<00:00,  7.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.05it/s]

                   all        648       1520      0.852      0.836      0.873      0.727



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     92/200      2.76G      0.448     0.3918      1.049          6        768: 100%|██████████| 543/543 [01:17<00:00,  6.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.62it/s]


                   all        648       1520      0.848      0.842      0.876      0.729

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     93/200      2.76G      0.459     0.4012      1.054          7        768: 100%|██████████| 543/543 [01:17<00:00,  6.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.58it/s]

                   all        648       1520      0.848      0.847      0.877      0.733



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     94/200      2.76G     0.4611     0.4014      1.056          9        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.78it/s]

                   all        648       1520      0.843      0.848      0.878      0.734



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     95/200      2.76G     0.4602     0.4018       1.05          6        768: 100%|██████████| 543/543 [01:20<00:00,  6.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.81it/s]

                   all        648       1520      0.844       0.83      0.869      0.729



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     96/200      2.76G     0.4628     0.4169      1.054          3        768: 100%|██████████| 543/543 [01:17<00:00,  6.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.77it/s]


                   all        648       1520      0.872      0.826      0.877       0.73

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     97/200      2.75G     0.4442     0.3806       1.04          4        768: 100%|██████████| 543/543 [01:18<00:00,  6.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.48it/s]

                   all        648       1520      0.871      0.832      0.885      0.736



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     98/200      2.75G     0.4503     0.4015      1.043         12        768: 100%|██████████| 543/543 [01:16<00:00,  7.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.91it/s]

                   all        648       1520      0.866      0.835       0.88      0.735



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     99/200      2.76G     0.4387     0.3722      1.035          4        768: 100%|██████████| 543/543 [01:18<00:00,  6.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.55it/s]

                   all        648       1520      0.894      0.818      0.881      0.744



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    100/200      2.75G     0.4556     0.3981      1.047          8        768: 100%|██████████| 543/543 [01:17<00:00,  7.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.85it/s]

                   all        648       1520      0.895      0.826      0.881      0.736



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    101/200      2.75G     0.4465     0.3897      1.048          6        768: 100%|██████████| 543/543 [01:16<00:00,  7.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.84it/s]

                   all        648       1520      0.874      0.825      0.874      0.731



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    102/200      2.74G     0.4361      0.379      1.038          7        768: 100%|██████████| 543/543 [01:17<00:00,  7.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.64it/s]

                   all        648       1520      0.874      0.826       0.88      0.736



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    103/200      2.76G     0.4318     0.3605      1.029         12        768: 100%|██████████| 543/543 [01:17<00:00,  7.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.87it/s]

                   all        648       1520      0.875      0.825      0.877      0.736



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    104/200       2.8G     0.4303     0.3591      1.027         11        768: 100%|██████████| 543/543 [01:17<00:00,  7.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.82it/s]

                   all        648       1520      0.832      0.859      0.877      0.732



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    105/200      2.76G     0.4438       0.37      1.039         10        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.82it/s]


                   all        648       1520      0.861      0.846      0.881      0.735

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    106/200      2.76G     0.4495     0.3829      1.042          6        768: 100%|██████████| 543/543 [01:17<00:00,  7.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.76it/s]

                   all        648       1520      0.855      0.841      0.876      0.731



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    107/200      2.76G     0.4399     0.3752      1.035         12        768: 100%|██████████| 543/543 [01:17<00:00,  7.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.71it/s]

                   all        648       1520      0.852      0.844      0.879       0.73



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    108/200      2.76G     0.4431     0.3877      1.049          7        768: 100%|██████████| 543/543 [01:17<00:00,  7.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.52it/s]

                   all        648       1520      0.861      0.842      0.878      0.735



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    109/200      2.75G     0.4381     0.3815      1.037          4        768: 100%|██████████| 543/543 [01:17<00:00,  6.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.73it/s]

                   all        648       1520      0.877      0.835      0.885      0.733



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    110/200      2.75G     0.4255      0.364      1.027          3        768: 100%|██████████| 543/543 [01:17<00:00,  7.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.81it/s]

                   all        648       1520      0.881      0.826      0.881      0.731



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    111/200      2.75G     0.4336     0.3764      1.034          3        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.73it/s]


                   all        648       1520      0.881      0.839      0.882      0.735

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    112/200      2.76G     0.4225     0.3713      1.027          4        768: 100%|██████████| 543/543 [01:17<00:00,  7.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.72it/s]

                   all        648       1520      0.878       0.82      0.878       0.73



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    113/200      2.76G     0.4229     0.3557      1.024         11        768: 100%|██████████| 543/543 [01:17<00:00,  7.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.87it/s]


                   all        648       1520      0.861      0.837       0.88      0.735

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    114/200      2.75G     0.4207     0.3683      1.025          3        768: 100%|██████████| 543/543 [01:17<00:00,  7.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.84it/s]

                   all        648       1520      0.877      0.836      0.883      0.734



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    115/200      2.75G     0.4254     0.3511      1.024          8        768: 100%|██████████| 543/543 [01:17<00:00,  6.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.74it/s]

                   all        648       1520      0.855      0.856      0.882      0.735



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    116/200      2.76G     0.4332     0.3788      1.034          5        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.65it/s]

                   all        648       1520      0.852      0.858      0.877      0.732



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    117/200      2.76G     0.4155     0.3568      1.014          5        768: 100%|██████████| 543/543 [01:17<00:00,  7.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.98it/s]

                   all        648       1520      0.885      0.841       0.88      0.737



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    118/200      2.74G     0.4215      0.364      1.027          6        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.91it/s]

                   all        648       1520      0.858      0.855      0.881      0.737



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    119/200      2.76G     0.4176     0.3587      1.023          4        768: 100%|██████████| 543/543 [01:17<00:00,  7.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.91it/s]

                   all        648       1520      0.849      0.861      0.881      0.734



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    120/200      2.79G     0.4091     0.3507      1.011          3        768: 100%|██████████| 543/543 [01:17<00:00,  7.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.51it/s]

                   all        648       1520       0.89      0.832      0.886      0.739



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    121/200      2.77G     0.4122     0.3472      1.018          7        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.65it/s]

                   all        648       1520      0.865      0.852      0.882       0.74



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    122/200      2.76G     0.4158     0.3551      1.019          4        768: 100%|██████████| 543/543 [01:16<00:00,  7.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.96it/s]

                   all        648       1520      0.864      0.847      0.882       0.74



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    123/200      2.76G     0.4048     0.3451      1.012          9        768: 100%|██████████| 543/543 [01:17<00:00,  7.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.69it/s]

                   all        648       1520      0.868      0.843      0.882       0.74



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    124/200      2.76G      0.419     0.3573      1.024          9        768: 100%|██████████| 543/543 [01:17<00:00,  7.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.78it/s]

                   all        648       1520      0.885      0.838      0.886      0.742



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    125/200      2.76G     0.4053     0.3454       1.01          3        768: 100%|██████████| 543/543 [01:17<00:00,  7.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.92it/s]

                   all        648       1520      0.882      0.832      0.885      0.742



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    126/200      2.76G     0.4158     0.3524      1.022          4        768: 100%|██████████| 543/543 [01:17<00:00,  7.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.86it/s]

                   all        648       1520       0.88      0.834      0.885      0.744



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    127/200      2.76G     0.4158     0.3455      1.016          3        768: 100%|██████████| 543/543 [01:17<00:00,  7.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.71it/s]

                   all        648       1520      0.875      0.843      0.887      0.743



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    128/200      2.76G     0.4135     0.3679      1.022          3        768: 100%|██████████| 543/543 [01:17<00:00,  6.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.82it/s]

                   all        648       1520      0.893      0.841      0.884      0.741



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    129/200      2.76G     0.4062     0.3476      1.004          5        768: 100%|██████████| 543/543 [01:17<00:00,  7.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.79it/s]

                   all        648       1520      0.869      0.845      0.882      0.742


EarlyStopping: Training stopped early as no improvement observed in last 30 epochs. Best results observed at epoch 99, best model saved as best.pt.
To update EarlyStopping(patience=30) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.

129 epochs completed in 3.126 hours.
Optimizer stripped from indonesian_food_yolov8\yolov8m_final_rerun\weights\last.pt, 52.0MB
Optimizer stripped from indonesian_food_yolov8\yolov8m_final_rerun\weights\best.pt, 52.0MB

Validating indonesian_food_yolov8\yolov8m_final_rerun\weights\best.pt...
Ultralytics YOLOv8.2.74  Python-3.10.11 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB)
Model summary (fused): 218 layers, 25,849,603 parameters, 0 gradients, 78.7 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:07<00:00, 10.31it/s]


                   all        648       1520      0.893      0.818      0.881      0.744
                 Bakso         24         25      0.954       0.92      0.916      0.693
                 Cakwe         33        201      0.827      0.542      0.744      0.572
          Dadar Gulung         19        125      0.827      0.648       0.76      0.631
           Ikan Goreng         53        119       0.83      0.697      0.762      0.578
                Klepon         44        383      0.845       0.58      0.752      0.597
         Lontong Sayur         34         34      0.884      0.912      0.934      0.884
        Martabak Manis         39        177      0.947      0.713      0.858      0.703
            Mie Goreng         34         37          1      0.779       0.95      0.866
           Nasi Padang         42         43      0.913      0.971      0.942      0.816
               Rendang         56         56      0.937      0.911      0.964      0.853
                 Riso

### Extended Fine-Tuning

In [1]:
from ultralytics import YOLO
import torch

# --- KONFIGURASI PATH ---
DATA_YAML_PATH = r"C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\data.yaml"

# PATH CHECKPOINT: Muat BEST.PT dari run sebelumnya ('yolov8m_final_rerun')
# Ini adalah bobot yang menghasilkan mAP 0.72886!
PREVIOUS_BEST_WEIGHTS = "indonesian_food_yolov8/yolov8m_final_rerun/weights/best.pt" 

# Muat model dari bobot TERBAIK sebelumnya
model = YOLO(PREVIOUS_BEST_WEIGHTS)

# GPU / CPU
device = 0 if torch.cuda.is_available() else "cpu"
print("Extended Fine-Tuning pada:", device)
print(f"Memuat bobot dari: {PREVIOUS_BEST_WEIGHTS}")

# =======================================================
# 1. START EXTENDED FINE-TUNING
# =======================================================

train_results = model.train(
    data=DATA_YAML_PATH,
    epochs=50,              # Durasi pelatihan lanjutan
    patience=10,            # Patience yang lebih ketat
    imgsz=768,              
    batch=4, 
    device=device,

    # 🔥 OPTIMASI UTAMA: TURUNKAN LR SANGAT RENDAH
    optimizer="AdamW",
    lr0=0.00005,            # Learning Rate diturunkan drastis
    cos_lr=True,
    warmup_epochs=5,
    weight_decay=0.0005,

    # 🔥 AUGMENTASI 
    hsv_h=0.012, hsv_s=0.6, hsv_v=0.35,
    degrees=4, translate=0.10, scale=0.40, shear=0.05, perspective=0.0,
    fliplr=0.5, flipud=0.15, 
    mosaic=0.10, mixup=0.05, erasing=0.10,           

    multi_scale=False,

    # 🔥 Logging
    project="indonesian_food_yolov8",
    name="yolov8m_extended_ft", # Nama folder baru untuk run Extended Fine-Tuning
    exist_ok=True,
)

print("\n✔ Extended Fine-Tuning Selesai!")


Extended Fine-Tuning pada: 0
Memuat bobot dari: indonesian_food_yolov8/yolov8m_final_rerun/weights/best.pt
New https://pypi.org/project/ultralytics/8.3.231 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.74  Python-3.10.11 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB)
engine\trainer: task=detect, mode=train, model=indonesian_food_yolov8/yolov8m_final_rerun/weights/best.pt, data=C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\data.yaml, epochs=50, time=None, patience=10, batch=4, imgsz=768, save=True, save_period=-1, cache=False, device=0, workers=8, project=indonesian_food_yolov8, name=yolov8m_extended_ft, exist_ok=True, pretrained=True, optimizer=AdamW, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True

train: Scanning C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\train\labels.cache... 2171 images, 0 backgrounds, 0 corrupt: 100%|██████████| 2171/2171 [00:00<?, ?it/s]

WARNING  Box and segment counts should be equal, but got len(segments) = 3235, len(boxes) = 4467. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.



val: Scanning C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\valid\labels.cache... 648 images, 0 backgrounds, 0 corrupt: 100%|██████████| 648/648 [00:00<?, ?it/s]

WARNING  Box and segment counts should be equal, but got len(segments) = 1100, len(boxes) = 1520. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.


Plotting labels to indonesian_food_yolov8\yolov8m_extended_ft\labels.jpg... 
optimizer: AdamW(lr=5e-05, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 768 train, 768 val
Using 8 dataloader workers
Logging results to indonesian_food_yolov8\yolov8m_extended_ft
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/50      2.79G     0.6126     0.6637       1.21          6        768: 100%|██████████| 543/543 [01:27<00:00,  6.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  7.73it/s]

                   all        648       1520      0.867      0.771      0.838      0.682



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/50       2.8G     0.5125     0.4879      1.101         14        768: 100%|██████████| 543/543 [01:22<00:00,  6.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:10<00:00,  8.02it/s]

                   all        648       1520      0.846      0.802      0.854      0.703



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/50      2.77G     0.4743     0.4268       1.06          3        768: 100%|██████████| 543/543 [01:24<00:00,  6.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.48it/s]


                   all        648       1520      0.877      0.839      0.881      0.735

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/50      2.76G     0.4353     0.3803      1.033         12        768: 100%|██████████| 543/543 [01:23<00:00,  6.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.44it/s]

                   all        648       1520      0.855      0.834      0.875      0.735



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/50      2.76G     0.4279     0.3645      1.028          7        768: 100%|██████████| 543/543 [01:22<00:00,  6.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.42it/s]


                   all        648       1520      0.861      0.829      0.878      0.738

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/50      2.75G     0.4402     0.3759      1.039          6        768: 100%|██████████| 543/543 [01:24<00:00,  6.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.64it/s]

                   all        648       1520      0.852      0.846       0.88      0.741



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/50      2.75G     0.4208     0.3735      1.027          5        768: 100%|██████████| 543/543 [01:20<00:00,  6.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.65it/s]

                   all        648       1520      0.869      0.824       0.88      0.741



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/50       2.8G     0.4193     0.3508      1.022          3        768: 100%|██████████| 543/543 [01:20<00:00,  6.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.49it/s]

                   all        648       1520      0.869      0.842      0.881      0.744



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/50      2.77G     0.4248     0.3602      1.027         12        768: 100%|██████████| 543/543 [01:19<00:00,  6.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.78it/s]

                   all        648       1520       0.87      0.839      0.879      0.743



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/50      2.76G     0.4243     0.3547      1.027         10        768: 100%|██████████| 543/543 [01:19<00:00,  6.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.75it/s]

                   all        648       1520      0.867      0.838      0.883      0.743



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/50      2.75G      0.428      0.377      1.034          3        768: 100%|██████████| 543/543 [01:19<00:00,  6.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.66it/s]

                   all        648       1520      0.855      0.853      0.882      0.741



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/50      2.76G     0.4183     0.3499      1.019          4        768: 100%|██████████| 543/543 [01:19<00:00,  6.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.54it/s]

                   all        648       1520      0.859       0.84      0.882      0.741



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/50      2.77G     0.4134     0.3462      1.019          7        768: 100%|██████████| 543/543 [01:19<00:00,  6.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.76it/s]

                   all        648       1520       0.86      0.843      0.879      0.737



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/50      2.76G     0.4173     0.3425       1.02          9        768: 100%|██████████| 543/543 [01:20<00:00,  6.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.44it/s]

                   all        648       1520      0.875       0.84      0.883      0.741



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/50      2.75G     0.4108     0.3459      1.014         15        768: 100%|██████████| 543/543 [01:19<00:00,  6.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.43it/s]

                   all        648       1520      0.865      0.836      0.879       0.74



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/50      2.75G     0.4128     0.3539      1.016          5        768: 100%|██████████| 543/543 [01:19<00:00,  6.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.63it/s]

                   all        648       1520      0.848      0.854      0.878       0.74



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/50      2.75G     0.4049     0.3456      1.013         10        768: 100%|██████████| 543/543 [01:20<00:00,  6.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.41it/s]

                   all        648       1520      0.866      0.842      0.881      0.741



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/50      2.76G     0.4088     0.3416      1.013          4        768: 100%|██████████| 543/543 [01:19<00:00,  6.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00,  9.49it/s]

                   all        648       1520      0.857      0.849      0.879       0.74
EarlyStopping: Training stopped early as no improvement observed in last 10 epochs. Best results observed at epoch 8, best model saved as best.pt.
To update EarlyStopping(patience=10) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.



18 epochs completed in 0.456 hours.
Optimizer stripped from indonesian_food_yolov8\yolov8m_extended_ft\weights\last.pt, 52.0MB
Optimizer stripped from indonesian_food_yolov8\yolov8m_extended_ft\weights\best.pt, 52.0MB

Validating indonesian_food_yolov8\yolov8m_extended_ft\weights\best.pt...
Ultralytics YOLOv8.2.74  Python-3.10.11 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB)
Model summary (fused): 218 layers, 25,849,603 parameters, 0 gradients, 78.7 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 81/81 [00:08<00:00, 10.07it/s]


                   all        648       1520      0.868      0.843      0.881      0.744
                 Bakso         24         25      0.786       0.88      0.857       0.67
                 Cakwe         33        201      0.742      0.721      0.756      0.571
          Dadar Gulung         19        125      0.811      0.664      0.762      0.642
           Ikan Goreng         53        119      0.775      0.697       0.75      0.603
                Klepon         44        383      0.851      0.599      0.773       0.61
         Lontong Sayur         34         34      0.887      0.882      0.927      0.864
        Martabak Manis         39        177      0.945      0.679      0.852      0.688
            Mie Goreng         34         37      0.972      0.932      0.952      0.851
           Nasi Padang         42         43      0.864      0.953      0.968      0.827
               Rendang         56         56      0.958      0.946      0.979      0.847
                 Riso

## **Evaluasi pada Split test**

In [7]:
from ultralytics import YOLO
import torch # Diperlukan untuk mengecek device jika Anda menjalankan code di lingkungan lokal

# --- KONFIGURASI PATH ---
# GANTI PATH ke BEST.PT dari run Extended Fine-Tuning terakhir Anda
MODEL_PATH = "indonesian_food_yolov8/yolov8m_extended_ft/weights/best.pt"
DATA_YAML_PATH = r"C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\data.yaml"

# Muat model terbaik
model = YOLO(MODEL_PATH)

print("Memulai Evaluasi Resmi pada Split 'test'...")

# Jalankan evaluasi
metrics = model.val(
    data=DATA_YAML_PATH, 
    split='test', 
    imgsz=768, 
    conf=0.001,
    iou=0.7,
    # Anda juga bisa menambahkan argumen save_json=True untuk detail lebih lanjut
)

# --- EKSTRAKSI DAN CETAK METRIK DENGAN PENGKOREKSIAN VALUEERROR ---

# Ambil nilai rata-rata global yang dijamin scalar:
p = metrics.box.p.mean()      # Precision (mengambil nilai rata-rata jika p adalah array)
r = metrics.box.r.mean()      # Recall (mengambil nilai rata-rata jika r adalah array)
map50 = metrics.box.map50     # mAP50 (sudah scalar)
map95 = metrics.box.map       # mAP50-95 (sudah scalar)

# Hitung F1-score: F1 = 2 * (Precision * Recall) / (Precision + Recall)
# Pengecekan ini kini aman karena p dan r sudah dipastikan scalar (nilai tunggal).
if (p + r) > 0:
    f1_score = 2 * (p * r) / (p + r)
else:
    f1_score = 0.0

Memulai Evaluasi Resmi pada Split 'test'...
Ultralytics YOLOv8.2.74  Python-3.10.11 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3070 Ti Laptop GPU, 8192MiB)
Model summary (fused): 218 layers, 25,849,603 parameters, 0 gradients, 78.7 GFLOPs


val: Scanning C:\Users\macin\OneDrive - Universitas Pelita Harapan\Documents\NeuralNetwork\Food Recognation\food-recognition-AML\Food Dataset\test\labels.cache... 329 images, 0 backgrounds, 0 corrupt: 100%|██████████| 329/329 [00:00<?, ?it/s]

WARNING  Box and segment counts should be equal, but got len(segments) = 562, len(boxes) = 751. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.



                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 21/21 [02:07<00:00,  6.07s/it]


                   all        329        751      0.885      0.848      0.891      0.752
                 Bakso         10         10      0.814        0.9      0.872      0.563
                 Cakwe         21        113      0.707      0.699       0.75      0.514
          Dadar Gulung         16        100      0.976       0.73      0.898      0.794
           Ikan Goreng         23         46      0.781      0.587      0.652      0.509
                Klepon         18        157      0.971      0.629      0.866      0.737
         Lontong Sayur         20         22        0.9      0.864      0.883      0.815
        Martabak Manis         19         52      0.895      0.827      0.887      0.758
            Mie Goreng         17         18      0.966      0.944       0.99      0.894
           Nasi Padang         21         21      0.986          1      0.995      0.832
               Rendang         27         32      0.907      0.781      0.809       0.73
                 Riso

In [8]:
print("\n=======================================================")
print("✅ HASIL EVALUASI FINAL PADA DATA TEST")
print("=======================================================")
print(f"Precision (p): {p:.5f}")
print(f"Recall (r):    {r:.5f}")
print(f"F1-Score:      {f1_score:.5f}")
print("-------------------------------------------------------")
print(f"mAP50:         {map50:.5f}")
print(f"mAP50-95:      {map95:.5f}")
print("=======================================================")


✅ HASIL EVALUASI FINAL PADA DATA TEST
Precision (p): 0.88513
Recall (r):    0.84761
F1-Score:      0.86596
-------------------------------------------------------
mAP50:         0.89074
mAP50-95:      0.75249
